algolia/algoliasearch-magento-2

Helper/ConfigHelper.php, Helper/Data.php, Model/Indexer/Category.php, Model/Indexer/Product.php, Model/Source/AbstractTable.php, Model/Source/Facets.php
=> Producthelper class does not exists #3

Helper/Entity/ProductHelper.php, dev/Dockerfile, dev/bin/start.sh
=> Enable mod_rewrite to unite CLI and web generated URLs. 

Adapter/Algolia.php
=> Fix document creation in version >=2.1.0

Helper/ConfigHelper.php, Helper/Entity/BaseHelper.php
=> Use different column names for CC and EE>=2.1 - fixes compatibility

Helper/Entity/CategoryHelper.php
#99 : Handle properly option "Show categories that are not included in the navigation menu" for category reindexation
=> Fix for issue #99 

view/frontend/web/instantsearch.js, view/frontend/web/internals/common.js
=> Add HTML classes to widget containers

Helper/ConfigHelper.php
=> Fix images config paths

Helper/ConfigHelper.php
=> Dispatch new algolia_get_retrievable_attributes event

README.md
=> Support Magento >= 2.1

etc/adminhtml/system.xml
=> Show all configuration options in website and store views

Helper/Entity/PageHelper.php
=> Index correct CMS pages for specific store views

etc/config.xml
=> Enable SEO request by default

Helper/Entity/ProductHelper.php
=> Send product type to algolia_subproducts_index event

view/frontend/templates/instant/hit.phtml, view/frontend/web/internals/algoliasearch.css
=> Fix ratings styles - show the products' rating on the IS page

Helper/Entity/ProductHelper.php
=> Index correct prices with applied catalog price rules

Helper/ConfigHelper.php
=> Return bool value from isAddToCartEnabled config

view/frontend/layout/algolia_search_handle.xml
=> Fix layout handle to include templates in Ultimo theme as well

Helper/Entity/ProductHelper.php
Fixes the issue with zero prices
=> Add finalPrice to products' collection

Helper/Entity/BaseHelper.php, Helper/Entity/PageHelper.php
=> Completely remove script and style tags from indexed pages' content

view/adminhtml/templates/adminjs.phtml
=> Fix requireJS issue in administration

Helper/ConfigHelper.php, Helper/Entity/CategoryHelper.php, Helper/Entity/PageHelper.php, Helper/Entity/ProductHelper.php
=> Fix secure URLs

Model/Indexer/Product.php, Test/Integration/QueueTest.php
Now when `execute` is called with large amount of `$productIds` only one job with all those IDs is created in `algoliasearch_queue` table. It might result in overloaded `data` column when the JSON is truncated and therefore not valid.
This PR makes sure, that when creating the job the `NumberOfElementByPage` is taken into account and one huge job is split into several smaller ones.
Fixes #219
=> Fix for overloaded queue jobs

Helper/Entity/BaseHelper.php, Helper/Entity/PageHelper.php, Test/Integration/PagesIndexingTest.php
=> Fix pages encoding

Helper/Entity/CategoryHelper.php, Helper/Entity/ProductHelper.php, Helper/Image.php
=> Fix image URLs indexed with double slashes

Helper/Entity/BaseHelper.php, Helper/Entity/ProductHelper.php
=> Fix prices in different currencies

Block/Configuration.php, view/frontend/layout/algolia_search_handle.xml, view/frontend/templates/internals/configuration.phtml
=> Refactored configuration.phtml [BC break]

view/frontend/web/autocomplete.js, view/frontend/web/instantsearch.js
=> Implement JS custom events / hooks [BC break]

view/frontend/templates/autocomplete/attribute.phtml, view/frontend/templates/autocomplete/category.phtml, view/frontend/templates/autocomplete/page.phtml, view/frontend/templates/autocomplete/suggestion.phtml, view/frontend/templates/instant/hit.phtml, view/frontend/templates/instant/wrapper.phtml, view/frontend/web/internals/algoliasearch.css
=> Prefix CSS classes with Algolia-specific IDs [BC Break]

Helper/AlgoliaHelper.php, Helper/ConfigHelper.php, Helper/Data.php, Model/Backend/ExtraSettings.php, Model/Textarea.php, Test/Integration/ConfigTest.php, etc/adminhtml/system.xml
=> Add "Extra settings" feature

Helper/ConfigHelper.php
=> Fix return type of isEnabledBackend method

Block/Configuration.php, Helper/ConfigHelper.php, etc/adminhtml/system.xml, etc/config.xml, view/frontend/web/instantsearch.js
Fixes https://github.com/algolia/algoliasearch-magento-2/issues/239
Port of https://github.com/algolia/algoliasearch-magento/pull/754
It seems like `_gaq` (legacy) was dropped.
**[DOC]** To be merge with https://github.com/algolia/magento/pull/51
=> Introduce Analytics

Helper/Data.php, Helper/Entity/AdditionalSectionHelper.php, Helper/Entity/CategoryHelper.php, Helper/Entity/PageHelper.php, Helper/Entity/ProductHelper.php, Helper/Entity/SuggestionHelper.php
=> More granular backend events

Model/Indexer/Page.php
=> Don't index CMS pages when it's not set in additional sections

Helper/ConfigHelper.php, Helper/Entity/BaseHelper.php, Helper/Entity/ProductHelper.php, Helper/Entity/SuggestionHelper.php
=> Optimize popular queries

Helper/Data.php
=> Support of EE split databases feature

Helper/Data.php
In fact this is another way to fix the problem reported in #274
=> fixing price calculations

Helper/Entity/ProductHelper.php
=> Fix undefined "order" index

Helper/ConfigHelper.php, Model/Source/Sorts.php, Setup/UpgradeSchema.php, Test/Integration/ConfigTest.php
=> Fix sorts / facets labels mix up

Adapter/Algolia.php, Helper/ConfigHelper.php, Helper/Data.php
=> Restrict search adapter

Helper/Entity/ProductHelper.php
=> No SID in URL

Block/Algolia.php, Helper/Entity/ProductHelper.php
There is a problem when customer group has been specified in a catalog price rule so I fixed it up
=> Fix special prices

Helper/Entity/ProductHelper.php
=> Fix grouped products prices

view/frontend/templates/autocomplete.phtml, view/frontend/web/internals/algoliasearch.css
=> Make the cart clickable on mobile devices

Helper/Data.php, etc/view.xml
=> Fix placeholder image indexed URL

Model/Queue.php
=> Change EMPTY_QUEUE constant name to more descriptive PROCESS_FULL_QUEUE

Block/Algolia.php, Block/Configuration.php, view/frontend/web/internals/common.js
=> Fix expired special prices

Adapter/Algolia.php, phpstan-travis-2.0.neon
New handle of connection errors in the adapter
=> Handle connection error

Model/Product/Url.php
=> Remove _scope_to_url param as it added useless parameters to URLs

Block/Algolia.php, Block/Configuration.php, view/frontend/web/instantsearch.js, view/frontend/web/internals/algoliasearch.css
=> Format price on slider facets

Helper/Entity/ProductHelper.php
Right now SKUs of child products are ignored and not indexed withing a configurable product array. This commit indexes SKUs and colors of child products no matter if it is defined in parent product.
=> Correctly index child attributes' values

Helper/ConfigHelper.php, Helper/Entity/Product/PriceManager.php, Helper/Entity/Product/PriceManager/Bundle.php, Helper/Entity/Product/PriceManager/Configurable.php, Helper/Entity/Product/PriceManager/Downloadable.php, Helper/Entity/Product/PriceManager/Grouped.php, Helper/Entity/Product/PriceManager/ProductWithChildren.php, Helper/Entity/Product/PriceManager/ProductWithoutChildren.php, Helper/Entity/Product/PriceManager/Simple.php, Helper/Entity/Product/PriceManager/Virtual.php, Helper/Entity/ProductHelper.php, view/frontend/templates/autocomplete/product.phtml, view/frontend/templates/instant/hit.phtml, view/frontend/web/internals/algoliasearch.css
=> Price manager refactoring

Plugin/SearchHelperDataPlugin.php, etc/di.xml
=> Fix rendering of "__empty__" query to a front-end

view/frontend/web/internals/common.js
Remove "ors" category links when the categories facet is not active
=> Fix autocomplete bottom links

Block/Algolia.php, view/frontend/web/internals/common.js
Fix display of special price when special_to_date is equal to the current date (related to issue #618)
=> Fix display of special price 

Block/Configuration.php, Helper/ConfigHelper.php
Fix customer group price sorting
=> Fix customer group price sorting on frontend

Helper/Adapter/FiltersHelper.php
Remove forgotten isSearch() function (related to issue #648 ) .
=> Fix Adapter FilterHelper

Helper/Entity/Product/AttributeHelper.php
Fix the bug that prevents the user to select 2 values in the facets when Instantsearch is not activated on frontend.
=> Fix Attribute Helper 

Helper/AlgoliaHelper.php, Helper/Data.php, Helper/Entity/ProductHelper.php, Model/Indexer/Category.php, Model/Indexer/Product.php, Model/IndicesConfigurator.php, Model/Observer/SaveSettings.php, Test/Integration/ConfigTest.php, Test/Integration/QueueTest.php
- Improved logging
- Extracted to standalone class
- "Data" helper is not responsible for "set settings" anymore
=> Refactored "set settings"

Helper/ConfigHelper.php
=> Fix types returned from ConfigHelper

Helper/ConfigHelper.php
=> Prevent failing on missing user agent

.travis.yml
I don't see any added value in Travis Buddy. Do you feel the same or does it help you?
=> Remove TravisBuddy

Exception/CategoryEmptyException.php, Exception/CategoryNotActiveException.php, Exception/CategoryNotIncludedInMenuException.php, Exception/CategoryReindexingException.php, Helper/Data.php, Helper/Entity/CategoryHelper.php, Model/Indexer/Category.php, Model/Indexer/Product.php
=> Refactor categories to be indexed by batches

i18n/en_US.csv, view/frontend/templates/instant/hit.phtml
**Summary**
Translate text in template for i18n translation. 
Related Issue: #701 
**Result**
Update the hit template for translation and review other templates for any text that hasn't been translated.
=> Translate html text in hit template

view/adminhtml/layout/algolia_algoliasearch_handle_access_denied.xml, view/adminhtml/templates/landingpage/suggestions.phtml, view/adminhtml/web/css/landing-page.css
**Summary**
[MAG-123] Remove "Access Denied" in limited LPB screen
[MAG-121] Update empty count state to move blue info message to the centre  
**Result**
- Updated layout to update Title for denied controller. 
- Updated suggestions template to add blue messaging inside empty collection condition.
[MAG-123]: https://algolia.atlassian.net/browse/MAG-123
[MAG-121]: https://algolia.atlassian.net/browse/MAG-121
=> LPB Admin Page Updates

view/adminhtml/templates/analytics/overview.phtml, view/adminhtml/web/css/analytics.css
- Empty query is now "visible"
- Improved copy of link to more "No results" searches
=> Better UX and copy on Analytics overview page

Helper/AlgoliaHelper.php
This will allow interceptor generation, and is considered best practice.
**Summary**
Use Factory to get the Client instead "new".
**Result**
You can now make plugins.
=> Use factory to create new AlgoliaSearch\Client

.travis.yml
- Remove composer deploy of sample data
=> Clone sample data

view/frontend/web/autocomplete.js, view/frontend/web/internals/common.js
Related to issue https://github.com/algolia/algoliasearch-magento-2/issues/745
=> Add afterAutocompleteStart hook

Model/Queue.php, Setup/UpgradeSchema.php, Test/Integration/QueueTest.php
=> Unlock stacked jobs after 15 minutes

view/adminhtml/web/js/support.js, view/frontend/web/internals/common.js
=> Change "let" for "var"

CHANGELOG.md, README.md, composer.json
=> Bump to 1.11.0

Helper/ProductDataArray.php, Model/Observer/CatalogPermissions/ProductPermissions.php
Missing key on set data and updated catalog vs shared permission logic order.
=> Fix on b2b catalogpermissions

Adapter/Algolia.php, Model/Observer/CatalogPermissions/ProductCollectionAddPermissions.php
Reverts algolia/algoliasearch-magento-2#791
=> Revert "Adding "total" to adapter queries (introduced by Magento 2.3)"

Model/Indexer/Category.php
**Summary**
On category update, productIds affected were not batched. Due to product indexing logic on for getProductsRecords, productIds not within the paged $collection are flagged for deletion. We need to batch the affected products to prevent loss of product data. 
**Result**
Updated \Algolia\AlgoliaSearch\Model\Indexer\Category::rebuildAffectedProducts() method to batch the productIds on category update.
=> Batch size proccess of affected products after category update

Factory/CatalogPermissionsFactory.php, Factory/SharedCatalogFactory.php, Model/Observer/CatalogPermissions/ApplyProductPermissionsFilter.php, Model/Observer/CatalogPermissions/CategoryCollectionAddPermissions.php, Model/Observer/CatalogPermissions/ProductCollectionAddPermissions.php
**Summary**
Update B2B permissions to include the allow browsing catalog scope. Add count checks before list to prevent notice errors.
Related Issues: #793
=> Update B2B permissions condition

.circleci/config.yml
Update Circle CI build and workflow to allow integration testing for community pull requests.
=> Update CircleCI Build

phpstan.neon
This pull request is a work in progress to add type checking into magento.
=> chore: adds type checking tool configuration

.circleci/config.yml
=> chore: fix run name

.circleci/config.yml
**Summary**
This PR will fix the CI checks currently failing, and adds the PHPStan analysis by @nunomaduro .
=> ci: quality assurance tools

.circleci/config.yml
This pull request fixes the build while using the new the tool `magento2-tools` version `^0.2.0`.
=> chore: fixes quality tools build

composer.json
Added "suggest" section with submodules as I suggested in PR #889, pt .2.
=> Add "suggest" section modules in composer.json

view/adminhtml/templates/queue/status.phtml
Added documentations links on top of the indexing queue page (same links as the indexing queue section in the magento configuration)
=> Added documentations links on top of the indexing queue page

Helper/ConfigHelper.php, Helper/Data.php, Model/Indexer/Product.php, Test/Integration/AssertValues/Magento_2_2.php, Test/Integration/AssertValues/Magento_2_3.php, Test/Integration/QueueTest.php
1. adding array_unique to remove duplicate productIds in indexing
2. add condition to check if facet configuration has value (#913)
3. update numericFilters parameter to pass array for count() php 7.2 error (#910)
4. add condition to check if customRankings configuration for product and category has value (#858)
=> Minor updates for optimization 

view/frontend/web/autocomplete.js
Removed extra callback for autocomplete:updated and join to 1 function.
=> Join 2 callbacks for autocomplete updated event

Model/Source/CustomRankingProduct.php, Model/Source/JobMethods.php, Model/Source/JobStatuses.php, Model/Source/LandingPageStatuses.php, Model/Source/RetryValues.php, Model/Source/SortOrderCategory.php, Model/Source/SortOrderProduct.php, Model/Source/Sorts.php, etc/adminhtml/menu.xml, view/adminhtml/ui_component/algolia_algoliasearch_landingpage_form.xml
Hi!
In adminhtml some phrases aren`t available for translation. In PR I added missed tags for menu, UI components descriptions and option grids/models.
Thnx!
=> Added translation in menu, Ui component. Source option models.

Test/Integration/CategoriesIndexingTest.php, Test/Integration/PagesIndexingTest.php, Test/Integration/ProductsIndexingTest.php, Test/Integration/QueueTest.php, Test/Integration/SearchTest.php, Test/Integration/TestCase.php
Hi,
Continue changes from PR #935 and fixes for unit tests. All classes were imported by use and using ::class makes  "getters" shorter and tests show if class will be removed  or its` name will be changed.
Thnx!
=> Tests: improve class names usage and replace literal name to ::class

Model/ExtensionNotification.php, composer.json
Two changes in the ExtensionNotification class :
- Use Guzzle to perform the call to Github API
- Log the exception if there's any
=> Use Guzzle to for version checking

Helper/Configuration/AssetHelper.php, Model/Job.php, Model/ResourceModel/Run/Collection.php, Model/Run.php, view/adminhtml/templates/analytics/form.phtml, view/adminhtml/templates/analytics/graph.phtml, view/adminhtml/templates/analytics/overview.phtml, view/adminhtml/templates/catalog/category/edit/merchandising.phtml, view/adminhtml/templates/common.phtml, view/adminhtml/templates/configuration.phtml, view/adminhtml/templates/job/view.phtml, view/adminhtml/templates/landingpage/access_denied.phtml, view/adminhtml/templates/landingpage/cms-notice.phtml, view/adminhtml/templates/landingpage/page-settings-notice.phtml, view/adminhtml/templates/landingpage/search-configuration.phtml, view/adminhtml/templates/landingpage/suggestions.phtml, view/adminhtml/templates/merchandising/page.phtml, view/adminhtml/templates/query/access_denied.phtml, view/adminhtml/templates/query/banner-notice.phtml, view/adminhtml/templates/query/edit/merchandising.phtml, view/adminhtml/templates/query/suggestions.phtml, view/adminhtml/templates/queue/status.phtml, view/adminhtml/templates/support/components/legacy-version.phtml, view/adminhtml/templates/support/contact.phtml, view/adminhtml/templates/support/overview.phtml, view/adminhtml/templates/ui/upsell-plan.phtml, view/adminhtml/web/css/common.css
**Summary**
Fixed and improved a lot of thing in adminhtml templates:
1. Added XSS prevention (escapeHtml, escapeJs, etc) in templates
2. Added as it`s possible translations
3. Change $this usage to $block (Magento guidelines)
4. Moved inline styles to web/css/common.css
Please review,
Thnx!
=> Adminhtml improvements: XSS prevention, translations, etc

Helper/Entity/CategoryHelper.php, Helper/Entity/ProductHelper.php
Hi!
I've checked code and found 1 fix that merged to develop, but It'll be needed on 1.x version.
I've moved  changes from PR #864 to develop-1.x.
@bsuravech and @damcou,
Please review.
Thnx!
=> Backport fix for "Product Category Data - Include in Menu Configuration"

Helper/Entity/ProductHelper.php, Helper/ProductDataArray.php, Model/ExtensionNotification.php, composer.json
Backport PR(s):
- Use Guzzle to for version checking (#949)
- Add forgotten indexOutOfStockOptions() method behaviour (#954)
- Update productDataArray for b2b to address countable error and refactoring of class (#915)
=> Backport changes to 1.x

Factory/CatalogPermissionsFactory.php, Factory/SharedCatalogFactory.php, Model/Observer/CatalogPermissions/ApplyProductPermissionsFilter.php, Model/Observer/CatalogPermissions/CategoryCollectionAddPermissions.php, Model/Observer/CatalogPermissions/CategoryPermissions.php, Model/Observer/CatalogPermissions/ProductCollectionAddPermissions.php, Model/Observer/CatalogPermissions/ProductPermissions.php
B2B/Catalog permissions update raw SQL to use db methods. While updating, I found some condition errors that didn't filter visibility correctly. This should now index the correct permission value and filtering properly.
=> Update B2B / Catalog Permissions raw SQL 

Block/Configuration.php, view/frontend/web/internals/common.js
Added condition for insights URL to only append when click analytics is enabled.
=> Add insights parameters when click analytics is enabled

Helper/AlgoliaHelper.php
Add Disjunctive facets compatibility for PHP Client V2 (used when backend rendering is activated)
=> Add Disjunctive facets compatibility for PHP Client V2

Factory/CatalogPermissionsFactory.php, Factory/SharedCatalogFactory.php, Helper/Entity/ProductHelper.php, Model/Observer/CatalogPermissions/ApplyProductPermissionsFilter.php, Model/Observer/CatalogPermissions/CategoryCollectionAddPermissions.php, Model/Observer/CatalogPermissions/CategoryPermissions.php, Model/Observer/CatalogPermissions/ProductCollectionAddPermissions.php, Model/Observer/CatalogPermissions/ProductPermissions.php, Model/Observer/CleanCatalogImagesCacheAfter.php, etc/adminhtml/events.xml
Upping the develop branch with fixes from develop-1.x
- Add warning after image cache is flushed (#983)
- Fix bundle product selections for subproducts (#982)
- Fixes visibility in B2B / Catalog Permissions raw SQL (#977)
=> Update develop with develop-1.x

CHANGELOG.md, README.md, composer.json, etc/module.xml
With the release of a new major version, we have decided to create minor and major version releases to allow those that want to continue on the minor version. This update will **break compatibility**. Please read the [upgrade guide](https://www.algolia.com/doc/integration/magento-2/getting-started/upgrading/#upgrading-from-v1-to-v2) for all of the file changes and updates included in this release. 
If you would like to stay on the minor version, please upgrade your composer to only accept versions less than version 2 like the example:
`"algolia/algoliasearch-magento-2": ">=1.13.1 <2.0"`
- Algolia PHP Client v2 (from v1) (#848, #968, #984, #990) @DevinCodes  
- [Instantsearch v4](https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/js/) (from v2) (#838, #912) @tkrugg
- …
=> Release 2.0.0

.circleci/config.yml
Backport PR#997 quality tools issues onto develop-1.x branch.
=> Backport CircleCI changes

Helper/ConfigHelper.php
Backport for 1.x, Issue  #1024
=> Prevent division by zero in the Notice Helper

Helper/AlgoliaHelper.php
Related to PR in M1: https://github.com/algolia/algoliasearch-magento/pull/1161
=> Fix query rules empty array by using copyRules method

.circleci/config.yml
Remove composer set and install lines as the image already has Magento installed.
=> Update CircleCI quality tools to remove composer set and install 

etc/mview.xml
=> Removed obsolete trigger for catalog_product_entity_media_gallery

etc/csp_whitelist.xml
Thanks @vmalyk for the v1.x PR! 
This is the backport(up-port?) for v2 PR #1036
=> Added CSP whitelisted hosts for Magento 2.3.5 or higher

Helper/Data.php
Thanks to @whadziewicz for his work on PR#1021! 
This PR is to replace #1021 to correct code styling as well as converting the raw SQL to use db connection methods.
=> Refactor getSalesData() method for optimisation

Helper/Entity/ProductHelper.php
=> Fix ProductHelper for bundle subproducts error

Helper/Data.php
Backport for v 1.x of PR #1034.
=> Backport - Refactor getSalesData() method for optimisation 

Helper/MerchandisingHelper.php
Backport for #1043 to add `filterPromotes` for query rules.
=> Activate "filterPromotes" attribute for created Merchandising Rules

.github/CONTRIBUTING.md, README.md
- Updated readme file to add Need Help? section and where to go for support. 
- Updated contribution file to add quality tools and change out Travis CI for CircleCI.
=> Update readme and contribution

.github/CONTRIBUTING.md, README.md
=>  Update readme and contribution

Helper/Entity/ProductHelper.php, Model/IndexMover.php
Backporting to v1.x:
- Check the right storeId for moveIndex (#1016)
- Add category_without_path only if categories is searchable (#969)
=> Backport to 1.x Community PRs

.circleci/config.yml
Backport for PR #1032 &  #1033.
=> Backport CircleCI changes 

.circleci/config.yml, .github/CONTRIBUTING.md, CHANGELOG.md, Helper/AlgoliaHelper.php, Helper/ConfigHelper.php, Helper/Data.php, Helper/Entity/ProductHelper.php, Helper/MerchandisingHelper.php, Model/IndexMover.php, Model/Source/Facets.php, README.md, composer.json, etc/csp_whitelist.xml, etc/module.xml, etc/mview.xml, view/frontend/web/instantsearch.js, view/frontend/web/internals/autocomplete.css
- Update the copyQueryRules method to use api client copyRules (#1029) 
- Removed obsolete trigger for catalog_product_entity_media_gallery from mview.xml (#1027) @vmalyk
- Add csp_whitelist for services (#1039) 
- Refactor getSalesData() method for optimisation (#1034) 
- Activate "filterPromotes" attribute for created Merchandising Rules (#1043)
- Add category_without_path only if categories is searchable (#969) @VincentMarmiesse
- Prevent division by zero in the Notice Helper when configuration is not set (#1026)
- Remove extra css import (#1013) @palviggi-flagbit
- Bundle products collection to return getItems array (#1038) 
- Switch from priceRanges to input ranges widget for ISV4 (#1042) 
- Check the right storeId for moveIndex (#1016) @palviggi-flagbit
- Remove composer self-update …
=> Release 2.0.1

composer.json
**Summary**
Added suggestion by Composer for MSI.
=> Added  algolia/algoliasearch-inventory-magento-2 to suggested modules

Helper/Entity/ProductHelper.php, Helper/MerchandisingHelper.php
JIRA Ticket: MAGE-6 
Convert rules to pass in `conditions` which is an array of `condition` parameters. Backward compatibility for `condition`.
=> Update for multi-condition rules

Model/Source/AbstractTable.php, etc/config.xml
- Added row ids "on the fly" for config serialized array when row id is missing
- Added some default values in config.xml
=> Fix serialization issue with 2.4

Helper/Entity/ProductHelper.php
JIRA Ticket: MAGE-42
Add image type check for value to skip if placeholder for subproduct images for color.
=> Update subproduct adaptive images on color

composer.json, etc/acl.xml
Grouped @vmalyk 's following PRs:
- Backport: Added algolia/algoliasearch-inventory-magento-2 to suggest #1075
- Remove PHP requirements from Composer #1077
- Set ACL resource titles are translatable. #1080
=> Grouped vmalyk's PRs  #1075, #1077, #1080

README.md
Add handy reference of library version for each versions we have of the extension and quick links to the docs to help with customisation.
=> Add Customisation section to README.md 

Helper/Entity/ProductHelper.php, Helper/MerchandisingHelper.php
=> 1.x Backport - Update for multi-condition rules

Model/Job.php
=> 1.x Backport - Remove IdentityInterface from Indexing Queue Job model class

view/adminhtml/ui_component/algolia_algoliasearch_indexing_log_listing.xml, view/adminhtml/ui_component/algolia_algoliasearch_indexing_queue_listing.xml
- Removed status filtering on queue (MAGE-55)
- Fixed queue log export (MAGE-51)
=> Indexing queue grids fixes 

Block/Configuration.php
Added 
- isPreventBackendRenderingEnabled
- areOutOfStockOptionsDisplayed
- queue
- isEnabled
- nbOfJobsToRun
- retryLimit
- nbOfElementsPerIndexingJob
=> Added some configuration to algoliaConfig JS object

view/adminhtml/templates/analytics/form.phtml, view/adminhtml/templates/analytics/graph.phtml, view/adminhtml/templates/analytics/overview.phtml, view/adminhtml/templates/catalog/category/edit/merchandising.phtml
Ran the linter in the testing environment. These are the corrections made to pass the PHP CS tests on the 4 identified templates:
```
1) vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates/analytics/form.phtml
2) vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates/analytics/overview.phtml
3) vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates/analytics/graph.phtml
4) vendor/algolia/algoliasearch-magento-2/view/adminhtml/templates/catalog/category/edit/merchandising.phtml
```
JIRA Ticket: [MAGE-67]
[MAGE-67]: https://algolia.atlassian.net/browse/MAGE-67
=> Quality Tools template linter 

Helper/Image.php
Fixed https://github.com/algolia/algoliasearch-magento-2/pull/1101 PR (CS Fixer)
=> Bugfix: Configurable product with broken image when set to "no_selection" (Fixed PR #1101)

Model/Observer/Insights/CheckoutOnepageControllerSuccessAction.php
=> Added try/catch on CheckoutSuccess event

etc/csp_whitelist.xml
Hey!
Small fix and removing irrelevant duplication policy in config file.
Please review,
=> Merge 2 connect-src policy sections to 1 in csp_whitelist.xml

Model/Indexer/AdditionalSection.php, Model/Indexer/Category.php, Model/Indexer/DeleteProduct.php, Model/Indexer/Page.php, Model/Indexer/Product.php, Model/Indexer/QueueRunner.php, Model/Indexer/Suggestion.php, etc/module.xml
- clean up indexers to remove `use Magento;`
- update sequence for Magento_Indexer
=> Update Module Sequence and indexers

Helper/Entity/SuggestionHelper.php, etc/csp_whitelist.xml, etc/mview.xml
- Refactor `getPopularQueries()` by removing the unnecessary for loop and and slice. 
- Correct the mview class for `algolia_additional_sections` indexer
- remove duplicated whitelist connect-src policy
=> Refactor popular queries collection and mview class for additional_sections

view/frontend/web/internals/common.js
- check to see if color object key is defined to prevent errors
=> Fix adaptive image issue for updated bundle

Block/Configuration.php, Helper/AnalyticsHelper.php, Helper/Entity/CategoryHelper.php, Model/Backend/EnableClickAnalytics.php, ViewModel/Adminhtml/Analytics/Overview.php, view/adminhtml/templates/analytics/graph.phtml, view/adminhtml/web/css/analytics.css
- refactor loops to use `array_column` for single key fetch
- fix issues with analytics overview and allow access if plan does not return from API
=> Refactor loops and fix analytics overview issues

view/frontend/web/instantsearch.js
This is a duplicate of PR#1138. Giving credit to @NickdeK for the original fix.
=> Fix instantsearch rangeInput labels

.github/release.yml
Added release.yml for release notes automation.
=> Added release.yml for automating release notes.

.circleci/config.yml, .php-cs-fixer.php, Block/Adminhtml/Job/View.php, Block/Adminhtml/Queue/Status.php, Block/Navigation/Renderer/CategoryRenderer.php, Block/Navigation/Renderer/DefaultRenderer.php, Block/Navigation/Renderer/PriceRenderer.php, Block/Navigation/Renderer/SliderRenderer.php, Controller/Adminhtml/Reindex/Save.php, Helper/Adapter/FiltersHelper.php, Helper/AlgoliaHelper.php, Helper/AnalyticsHelper.php, Helper/Configuration/NoticeHelper.php, Helper/Data.php, Helper/Entity/CategoryHelper.php, Helper/Entity/Product/PriceManager/ProductWithoutChildren.php, Helper/MerchandisingHelper.php, Model/ExtensionNotification.php, Model/ImageUploader.php, Model/Indexer/Category.php, Model/Job.php, Model/LandingPage.php, Model/Observer/Merchandising.php, Model/Query.php, Model/Queue.php, Test/Integration/ConfigTest.php, Test/Integration/PagesIndexingTest.php, ViewModel/Adminhtml/Analytics/Overview.php, composer.json
MAGE-176, Algolia Search Composer update for Magento 2.4.4 dependencies
**Result**
Fixed guzzlehttp/guzzle conflict in Magento 2.4.4 and
=> Algolia Search Composer update for magento 2.4.4 dependencies

Test/Integration/AssertValues/Magento244.php, Test/Integration/AssertValues/Magento_2_01.php, Test/Integration/AssertValues/Magento_2_2.php, Test/Integration/AssertValues/Magento_2_3.php, Test/Integration/CategoriesIndexingTest.php, Test/Integration/ConfigTest.php, Test/Integration/PagesIndexingTest.php, Test/Integration/TestCase.php
=> MAGE-186 Integration Test fix

view/frontend/web/insights.js
=> MAGE-207 userToken not properly being sent with M2

CHANGELOG.md, etc/module.xml
=> Updated Change log

README.md
=> 3.3.0 Update Readme

CHANGELOG.md, README.md, Test/Integration/TestCase.php
=> Update/release 3.3.1

CHANGELOG.md, README.md, composer.json, etc/module.xml
=> Updated release version

CHANGELOG.md, README.md, composer.json, etc/module.xml
=> Release v3.4.0

CHANGELOG.md, README.md, composer.json, etc/module.xml
Pull in the latest from develop branch.
=> Pull in the latest from develop branch.

CHANGELOG.md, README.md, composer.json, etc/module.xml
Pull in latest from master branch.
=> Pull in latest from master branch.

CHANGELOG.md, README.md, composer.json, etc/module.xml
=> upgrade algolia php client

Block/Adminhtml/Category/Merchandising.php
=> MAGE-298 fixed explode() passes null issue

.circleci/config.yml, CHANGELOG.md, README.md, composer.json, etc/module.xml
=> 3.7.0 Release Changes

CHANGELOG.md, README.md, composer.json, etc/module.xml
=> release 3.8.0

Helper/Entity/ProductHelper.php, Model/Source/Facets.php
=> MAGE-327 implementation

Helper/Entity/ProductHelper.php, Model/Source/SynonymsFile.php
=> MAGE-344 implementation

etc/adminhtml/system.xml
=> Updated System Config comments

view/frontend/web/internals/common.js
=> fix MAGE-314

etc/csp_whitelist.xml
=> MAGE-359 - whitelist insights.algolia.io in csp

Setup/Patch/Data/UpdateMviewPatch.php, Setup/Patch/Schema/ConfigPatch.php, Setup/Uninstall.php
=> MAGE-375 - Fix issue with table prefix and code cleanup

view/frontend/web/internals/common.js
=> MAGE-326 fix

etc/adminhtml/system.xml
**Summary**
Add comment to explain that Click Analytics is free in admin config
=> Add comment to show Click Analytics is free

Plugin/StockItemObserver.php, etc/di.xml
=> Fix Magento 2.4.5 compatibility issue

view/frontend/web/internals/autocomplete.css, view/frontend/web/internals/common.js
=> Fix Mage-374 autocomplete issue

README.md, composer.json
=> Updated php client version in composer

view/frontend/web/autocomplete.js, view/frontend/web/insights.js
=> Fixed Click analytics issue in Autocomplete

view/adminhtml/templates/query/edit/merchandising.phtml
=> Fixed the Index name issue in query merchendizing

Helper/Configuration/AssetHelper.php
=> Added Releases notes in the magento dashboard

Observer/ReindexProductOnLastItemPurchase.php, Observer/ReindexProductOnLastItemPurchaseIfMsiDisable.php, etc/adminhtml/events.xml, etc/events.xml, etc/module.xml
=> MAGE-407 Reindex product when last item purchased

view/frontend/web/autocomplete.js, view/frontend/web/internals/template/autocomplete/products.js
=> Perso Click Implementation for autocomplete

CHANGELOG.md, README.md, composer.json, etc/module.xml
=> Updated 3.9.0 Release Code

view/frontend/templates/recommend/products.phtml, view/frontend/templates/recommend/widget/trends-item.phtml, view/frontend/web/recommend.js
=> Ajax Add to cart for recommended

view/frontend/web/internals/common.js
=> instant search loading issue when price is not retrievable

Model/Queue.php
=> MAGE-499 Max retries for queue fixes

Observer/Insights/CheckoutCartProductAddAfter.php
=> Duplicate Place Order Conversion for Group Products fix

Helper/Entity/CategoryHelper.php, Helper/Entity/ProductHelper.php
=> category reindexing issue when it is disabled in one store

Block/Algolia.php, Block/Configuration.php, Helper/AlgoliaHelper.php, Helper/ConfigHelper.php, Helper/Entity/SuggestionHelper.php, etc/adminhtml/system.xml, etc/config.xml
=> Dev release 3.9.1

view/frontend/web/internals/common.js
Reverts algolia/algoliasearch-magento-2#1278
=> Revert "Bugfix/mage 501"

Block/Configuration.php, view/frontend/web/autocomplete.js
Make placeholder text translatable in autocomplete
=> Search input placeorder translation issue fix

Controller/Adminhtml/Reindex/Save.php
Fix issue with enforcing sku reindex limit of 10
=> MAGE-526 - enforce max 10 sku limit in sku reindex form

Observer/ReindexProductOnLastItemPurchaseIfMsiDisable.php
=> Full reindexing trigger after order place if MSI is disabled

Block/Configuration.php, view/frontend/web/instantsearch.js
=> Updated the InstantSearch code for category page

view/frontend/web/internals/common.js
=> MAGE-501 Landing Page Price Issue fix

CHANGELOG.md, README.md, composer.json, etc/module.xml
=> Updated version and change log for release 3.10.1

Observer/Insights/CheckoutCartProductAddAfter.php, Observer/Insights/CheckoutCartProductAddBefore.php, Observer/Insights/CheckoutOnepageControllerSuccessAction.php, Observer/Insights/CustomerLogin.php, Observer/Insights/WishlistProductAddAfter.php
=> MAGE-556 - backwards compatible for older than php 7.4 (Ready to go)

Helper/Entity/Product/PriceManager/Bundle.php
=> Update Bundle Product Price logic

view/frontend/web/internals/instantsearch.v3.css
=> Remove Blank space from instant search page

etc/adminhtml/system.xml
=> Updated comment for non-castable attributes

view/frontend/web/internals/common.js
=> Fixed issue with wrong routing if searchBox is disable for search page

Controller/Adminhtml/Landingpage/Save.php
=> Fixed the Landing page save issue

view/frontend/web/internals/template/autocomplete/suggestions.js
Fixed section.label undefined issue in autocomplete menu
**Summary**
**Result**
=> Fixed section.label undefined issue in autocomplete menu

Controller/Adminhtml/Landingpage/Save.php
=> Revert "Fixed the Landing page save issue"

CHANGELOG.md, README.md, composer.json, etc/module.xml
=> Updated release notes for 3.10.2

CHANGELOG.md, README.md, composer.json, view/frontend/layout/algolia_algoliasearch_landingpage_view.xml
=> Fixed compatibility issue in landing page

view/frontend/web/instantsearch.js
=> Fix the rangeslider issue on instantsearch page

Helper/ConfigHelper.php, Helper/Entity/ProductHelper.php, view/frontend/templates/instant/hit.phtml, view/frontend/web/internals/common.js
=> Bundle product add to cart fix from instant search page

Helper/Data.php, Helper/Entity/ProductHelper.php
=> Added Condition for null rating_summary

view/frontend/web/autocomplete.js, view/frontend/web/internals/template/autocomplete/additional-section.js, view/frontend/web/internals/template/autocomplete/categories.js, view/frontend/web/internals/template/autocomplete/pages.js, view/frontend/web/internals/template/autocomplete/products.js, view/frontend/web/internals/template/autocomplete/suggestions.js
=> Updated autocomplete code

view/frontend/web/autocomplete.js
=> Fixed Turning off autocomeplete in the admin still tries to load other js throwing errors

view/frontend/web/instantsearch.js, view/frontend/web/internals/common.js, view/frontend/web/recommend.js
=> Updated code to handle undefined algoliaConfig

view/frontend/web/insights.js
=> Code fix for position in autocomplete

Helper/Configuration/AssetHelper.php
=> Updated autocomplete external source link in admin config

etc/adminhtml/system.xml
=> Updated dashboard link URL in configuration

view/frontend/web/internals/template/recommend/products.js
=> MAGE-656 - remove unnecessary config variable to call algoliaConfig directly

view/frontend/web/internals/template/recommend/products.js, view/frontend/web/recommend.js
=> Updated position in Recommend listing

Observer/Insights/CustomerLogin.php
=> Send logged in user token for click and conversion

CHANGELOG.md, Observer/Insights/CustomerLogin.php, README.md, composer.json, etc/module.xml, view/frontend/requirejs-config.js, view/frontend/templates/autocomplete.phtml, view/frontend/templates/instant/facet.phtml, view/frontend/web/insights.js, view/frontend/web/internals/template/recommend/products.js, view/frontend/web/recommend.js
=> Integration Test 3.10.4

Block/Configuration.php, Controller/Adminhtml/Queue/View.php, Controller/Adminhtml/QueueArchive/View.php, Helper/ConfigHelper.php, etc/adminhtml/system.xml, etc/config.xml, view/frontend/web/instantsearch.js
=> Hide Pagination if nbpages size is 1

Helper/Entity/Product/PriceManager/ProductWithoutChildren.php
=> reverted tier price

composer.json
=> Update the Algolia php client

Block/Configuration.php
=> Update SecuredAPI key logic

Helper/Entity/ProductHelper.php, Helper/Logger.php
=> MAGE-681 Fixing the error log

etc/module.xml
=> Update module version

Helper/ConfigHelper.php, Helper/Data.php, Model/IndicesConfigurator.php, etc/adminhtml/system.xml, etc/config.xml
=> MAGE-750 enable/disable query suggestions index

Helper/ConfigHelper.php, Helper/Data.php, Model/Indexer/Page.php, Model/IndicesConfigurator.php, etc/adminhtml/system.xml, etc/config.xml
=> Turn off Page Indexing

view/adminhtml/templates/merchandising/page.phtml
=> Add a banner in Merchandising section in Admin

Helper/AlgoliaHelper.php
=> Fix Error Message related to replica index appears in admin

Helper/Entity/Product/PriceManager/Bundle.php
=> Indexed bundled product prices correctly

Helper/Entity/Product/PriceManager/ProductWithoutChildren.php
=> Index only the currency selected for the store

view/adminhtml/templates/merchandising/page.phtml
=> Update Banner Content

CHANGELOG.md, view/adminhtml/templates/merchandising/page.phtml
=> Release/3.11.0 Update

Model/Indexer/CategoryObserver.php
=> Update CategoryObserver to fix new category create issue

Model/Indexer/CategoryObserver.php, view/adminhtml/templates/merchandising/page.phtml
=> MAGE-765 Manual QA failed on new category 

Helper/Entity/ProductHelper.php
=> Custom attributes not indexed with value 0 when the Catalog Input Type for Store Owner is set to "Text field"

view/frontend/web/instantsearch.js
Fix from Kitroyale (See https://github.com/algolia/algoliasearch-magento-2/pull/1431) 
Approved and verified- attaching to internal Jira for QA
=> MAGE-795 Fixes clear refinements button from not showing

Helper/InsightsHelper.php, Observer/Insights/CustomerLogout.php, etc/frontend/events.xml, view/frontend/web/insights.js
=> Fix issue with cookies not cleared when customer logs out

Helper/Entity/ProductHelper.php, Model/Backend/Sorts.php
=> Duplicate Replica Issue one set is standard and another is virtual

Helper/Entity/ProductHelper.php, Model/Backend/Sorts.php
Reverts algolia/algoliasearch-magento-2#1444
=> Revert "Duplicate Replica Issue one set is standard and another is virtual"

Helper/InsightsHelper.php, view/frontend/web/instantsearch.js
=> MAGE-808 Add to Cart issue on PLP Page

Helper/AlgoliaHelper.php, Helper/ConfigHelper.php, etc/adminhtml/system.xml, etc/config.xml
=> Created a way for customers to change timeout values for Algolia PHP Client

i18n/de_DE.csv
=> Add German translations

ViewModel/Recommend/Cart.php
=> PHP8.2 compatibility Issue

view/frontend/templates/internals/configuration.phtml
=> MAGE-822 Removed polyfill script

Helper/ConfigHelper.php, Helper/Entity/ProductHelper.php
=> Updated release code

composer.json, etc/module.xml
=> MAGE-832 Bump version

Helper/InsightsHelper.php, view/frontend/web/insights.js
**Summary**
MAGE-867 merged into 3.14.0-beta.1 before. In this PR MAGE-867 backported to 3.13.3
=> MAGE-881: Ensure token is sent for either click and conversions or perso

view/frontend/web/instantsearch.js, view/frontend/web/internals/common.js
Apply XSS 3.13.4 fix to 3.14.x
=> MAGE-932: XSS fix to beta

Block/Configuration.php, view/frontend/templates/recommend/cart/recommend_items.phtml
Looking similar added to cart page
=> MAGE-896: looking similar added to cart page

view/frontend/web/recommend.js
With this code change, when there is no recommendation, only title and empty placeholder will not show anymore
=> MAGE-901: showing title for empty recommendation issue addressed

view/frontend/templates/internals/configuration.phtml, view/frontend/templates/layer/view.phtml
Same as https://github.com/algolia/algoliasearch-magento-2/pull/1535 for 3.13.4.
=> mage-851: Fix inline scripts for 3.13.4

Model/Queue.php, view/adminhtml/templates/job/view.phtml
(3.14.0-beta version)
This PR includes fixes from:
- https://github.com/algolia/algoliasearch-magento-2/pull/1539
- https://github.com/algolia/algoliasearch-magento-2/pull/1538
Thanks a lot to @pikulsky for these 🙌
=> MAGE-937: Fixes for Queue (3.14.0-beta)

Model/Queue.php, view/adminhtml/templates/job/view.phtml
This PR includes fixes from:
- https://github.com/algolia/algoliasearch-magento-2/pull/1539
- https://github.com/algolia/algoliasearch-magento-2/pull/1538
Thanks a lot to @pikulsky for these 🙌
=> MAGE-937: Fixes for Queue

view/frontend/web/internals/common.js
This PR ports the change suggested by @sgeleon here: https://github.com/algolia/algoliasearch-magento-2/pull/1516
Added a small change (usage of if statement over ternary)
=> Bugfix/MAGE-948: DOM selector check

view/frontend/web/internals/common.js
Same as https://github.com/algolia/algoliasearch-magento-2/pull/1550 for 3.14.0
=> Bugfix/mage 948/dom selector 3.14

view/frontend/templates/recommend/cart/recommend_items.phtml, view/frontend/templates/recommend/products.phtml, view/frontend/templates/recommend/widget/trends-item.phtml, view/frontend/web/internals/recommend.css
Same as https://github.com/algolia/algoliasearch-magento-2/pull/1553 but for 3.14
=> Bugfix/mage 947/css fix 3.14

etc/csp_whitelist.xml
**Summary**
Community contribution for release/3.14.0
=> Removed polyfill.io from csp_whitelist, was forgotten in MAGE-822

CHANGELOG.md, README.md
**Summary**
- Introduced new admin groups to InstantSearch for improved UX
- Updated `ConfigHelper` to use new paths
- Added data patch to migrate old configurations
- Bugfix for query rule disable on facets with new admin groupings
- Added new sorting admin option via source model
- Added derived virtual replica enablement to `ConfigHelper` based on `ArraySerialized`
- Intro’d simplified data structures to avoid array diff mismatches
- Intro’d new `ReplicaManager` abstraction to map Magento sorting to Algolia replica configuration
- Removed dependencies in backend models to handle replica config updates in Algolia addressing stale data
- Added `ReplicaState` registry for tracking changes to sorting configuration to minimize number of replica build operations
- Added logic to preserve …
=> MAGE-959: readme and changelog updated

etc/adminhtml/system.xml
The overall approach here is slated to be revisited in the future, but in the meantime this PR seeks to eliminate an unsupported feature and clarify the confusing configuration setting for backend render.
=> MAGE-961 Clarify current backend rendering behavior

CHANGELOG.md, README.md
Updated change log and README with pending draft release.
=> Feature/mage 962 - RC2 updates

Helper/AlgoliaHelper.php, Setup/Patch/Data/RebuildReplicasPatch.php
Addresses missing credentials on replica rebuild.
=> Feature/mage 962 - RC3

CHANGELOG.md, README.md, composer.json, etc/module.xml
**Summary**
- Token clean up on session expiration 
- Query string append issue addressed
- Address base table not found in integration tests with CLI command classes issue addressed
- README.md updated
=> MAGE-1010: release version and release notes updated.

view/frontend/templates/recommend/cart/recommend_items.phtml, view/frontend/templates/recommend/products.phtml, view/frontend/templates/recommend/widget/looking-similar.phtml, view/frontend/templates/recommend/widget/trends-item.phtml
**Summary**
Recommend scripts referencing old location issue addressed
=> MAGE-1017: recommend location reference issue addressed.

view/frontend/templates/recommend/cart/recommend_items.phtml, view/frontend/templates/recommend/products.phtml, view/frontend/templates/recommend/widget/looking-similar.phtml, view/frontend/templates/recommend/widget/trends-item.phtml
**Summary**
Add recommend patch to release/3.14.1
=> Bugfix/mage 1017 patch for 3.14.1

CHANGELOG.md, README.md
Updating change log for Github release.
=> MAGE-1010 Update changelog

view/frontend/templates/recommend/cart/recommend_items.phtml, view/frontend/templates/recommend/products.phtml, view/frontend/templates/recommend/widget/looking-similar.phtml, view/frontend/templates/recommend/widget/trends-item.phtml
=> Bugfix/mage 1017 patch for 3.14.0

CHANGELOG.md, README.md, composer.json, etc/module.xml
**Release Notes:**
**Updates:**
- Trained model check before enabling recommend.
=> MAGE-1018: release version upgraded to 3.14.2

Block/Algolia.php
Clarify intended type via import alias.
=> MAGE-1023 Use alias to clearly distinguish type

Helper/Entity/CategoryHelper.php
This PR fixes a bug discovered by @igorfigueiredogen regarding Category collection fetching
See more in the original PR: https://github.com/algolia/algoliasearch-magento-2/pull/1582
=> MAGE-970: Fix Category collection fetching

Test/Integration/Search/SearchTest.php
**Summary**
Category search integration test included.
=> MAGE-1050: category search test included.

composer.json
**Summary**
PHP client version updated from "^4.0@beta" to "^4.0"
=> MAGE-992: php client version updated

CHANGELOG.md, README.md, composer.json, etc/module.xml
=> MAGE-1092 Update extension for 3.13.6 release

CHANGELOG.md, README.md, composer.json, etc/module.xml
=> MAGE-1078: update extension for 3.14.3 release

view/frontend/web/js/internals/common.js
Same changes as this PR https://github.com/algolia/algoliasearch-magento-2/pull/1652 for `3.14.4`
=> MAGE-1101: change getCookie method (3.14.4)

view/frontend/web/internals/common.js
Same changes as this PR https://github.com/algolia/algoliasearch-magento-2/pull/1652 for 3.13.7
=> MAGE-1101: change getCookie method (3.13.7)

Helper/AlgoliaHelper.php
This PR is to backport the changes from: https://github.com/algolia/algoliasearch-magento-2/pull/1658
=> MAGE-1153 additional synonym use cases (3.14.4)

Helper/AlgoliaHelper.php
These additional settings were identified from end user feedback on PR https://github.com/algolia/algoliasearch-magento-2/pull/1656/
=> MAGE-1153 additional synonym use cases

Helper/ConfigHelper.php, Helper/Data.php, Model/Config/AutomaticPriceIndexingComment.php, Service/Product/MissingPriceIndexHandler.php, etc/adminhtml/system.xml, etc/config.xml, etc/indexer.xml
Backports https://github.com/algolia/algoliasearch-magento-2/pull/1662 for release 3.13.7.
=> MAGE-1122 Backport intentional price indexing to v3.13

Plugin/AddToCartRedirectForInsights.php, etc/frontend/di.xml, view/frontend/templates/instant/hit.phtml
This PR backports changes from https://github.com/algolia/algoliasearch-magento-2/pull/1667/commits for 3.14.4.
=> MAGE-1097: Handle add to cart redirect for Insights (3.14.4)

Service/Product/MissingPriceIndexHandler.php
Addresses PHP complaint per [Magento Coding Standard](https://experienceleague.adobe.com/en/docs/commerce-operations/upgrade-guide/upgrade-compatibility-tool/reporting/error-messages).
=> MAGE-1179 3.14 release prep - Address phpcs complaint

Service/Product/MissingPriceIndexHandler.php
Addresses PHP complaint per [Magento Coding Standard](https://experienceleague.adobe.com/en/docs/commerce-operations/upgrade-guide/upgrade-compatibility-tool/reporting/error-messages) (adding to v3.15).
=> MAGE-1179 Address PHPCS complaint (for 3.15)

CHANGELOG.md, README.md, composer.json, etc/module.xml
=> MAGE-1179: update extension for 3.14.4 release

Plugin/AddToCartRedirectForInsights.php, etc/frontend/di.xml, view/frontend/templates/instant/hit.phtml
This PR backports changes from https://github.com/algolia/algoliasearch-magento-2/pull/1667/commits for 3.13.7.
=> MAGE-1097: Handle add to cart redirect for Insights (3.13.7)

CHANGELOG.md, README.md, composer.json, etc/module.xml
=> MAGE-1183: update extension for 3.13.7 release

view/frontend/web/js/instantsearch.js
- Fixed a bug where the highlighting of the category facet wasn't working as expected.
=> MAGE-1169: fix category highlighting on search page

Api/Builder/IndexBuilderInterface.php, Api/Builder/RecordBuilderInterface.php, Api/Builder/UpdatableIndexBuilderInterface.php, Service/AdditionalSection/IndexBuilder.php, Service/AdditionalSection/RecordBuilder.php, Service/Category/IndexBuilder.php, Service/Category/RecordBuilder.php, Service/Page/IndexBuilder.php, Service/Page/RecordBuilder.php, Service/Product/IndexBuilder.php, Service/Product/RecordBuilder.php, Service/Suggestion/IndexBuilder.php, Service/Suggestion/RecordBuilder.php
- Removed folders `Api/IndexBuilder` and `Api/RecordBuilder`
- Introduced folder `Api/Builder `and moved all builders interfaces in it.
=> MAGE-1203: Builder folder reorganization 

README.md
Updating stale demo environment URL
=> Demo URL update

Helper/Entity/Product/PriceManager/ProductWithoutChildren.php
Backports changes from https://github.com/algolia/algoliasearch-magento-2/pull/1704 for 3.14.5
=> MAGE-1217: Fix excluded websites feature for price indexing (3.14.5)

Helper/Entity/Product/PriceManager/ProductWithoutChildren.php
Backports changes from https://github.com/algolia/algoliasearch-magento-2/pull/1704 for 3.16.0
=> MAGE-1217: Fix excluded websites feature for price indexing (3.16.0) 

CHANGELOG.md, composer.json, etc/module.xml
=> MAGE-1228: update extension for 3.15.0 release

CHANGELOG.md
- Updated README for 3.15.0-rc2
=> MAGE-1228: update readme for 3.15.0-rc2

etc/cron_groups.xml
- Added missing `cron_groups.xml` file with the new `algolia` group.
=> MAGE-347: Add cron_groups.xml file

Test/Unit/Service/ReplicaManagerTest.php
**Summary**
Small change to amend unit tests for bug identified on detach replicas.
**Result**
Unit test result:
=> MAGE-1251 Update unit tests

CHANGELOG.md, README.md, composer.json, etc/module.xml
Updates for upcoming beta release.
=> MAGE-1262 Update version info and change log

Model/RecommendManagement.php, Observer/RecommendSettings.php, etc/di.xml
**Summary**
This PR ports https://github.com/algolia/algoliasearch-magento-2/pull/1750 to 3.15 with one small addition: namely writing logs to the Algolia log (used for non admin contexts -  edge case). 
**Result**
=> MAGE-1201 Recommend model validation fix → 3.15

CHANGELOG.md, README.md, composer.json, etc/module.xml
=> MAGE-1267: updating extension for 3.14.5 release

Helper/Configuration/NoticeHelper.php
This PR fixes a small typo on the NoticeHelper.php file.
=> MAGE-1345: fix personalization typo

Service/Product/IndexBuilder.php
Ports fix from https://github.com/algolia/algoliasearch-magento-2/pull/1774 to 3.17.0
=> MAGE-1357 full reindex dropped catalog fix for 3.17.0

CHANGELOG.md, Model/Product/Url.php
**Summary**
- Backports community supplied fix from https://github.com/algolia/algoliasearch-magento-2/pull/1796 to 3.15
=> MAGE-1422 Product URL fix for 3.15.2

.codacy.yml
**Summary**
Instruct Codacy to ignore unit and integration tests and files not sent to Marketplace .
=> MAGE-1383 codacy ignore
