algolia/algoliasearch-magento-2

Model/Indexer/Page.php
Right now all pages on all stores are queued to reindex, But `\Algolia\AlgoliaSearch\Helper\Entity\BaseHelper::getStoreUrl` will result in null instead of `\Magento\Framework\Url` for inactive stores. That's why we have to queue only active stores
=> Only index pages on active store

Helper/ConfigHelper.php
If `Magento\Framework\App\ProductMetadata` used directly then the `$this->productMetadata->getEdition();` will always return `Community` (see https://github.com/magento/magento2/blob/develop/lib/internal/Magento/Framework/App/ProductMetadata.php#L24).
If `Magento\Framework\App\ProductMetadataInterface` used instead then:
- in Community Edition the object manager will return the `Magento\Framework\App\ProductMetadata` and the `getEdition` will return `Community`
- in Enterprise Edition the object manager will return the `Magento\Enterprise\Model\ProductMetadata` (because of this preference: `<preference for="Magento\Framework\App\ProductMetadataInterface" type="Magento\Enterprise\Model\ProductMetadata"/>`) and the `getEdition` method of that class will return `Enterprise`
=> Fix config helper to use ProductMetadataInterface to get the correct dependecy

Model/Queue.php
Fixes the issue, when queue settings are set high, jobs are created and then put back to low. Currently it won't process any jobs and jobs are stuck in DB table.
This PR will ensure that at least one job will be processed every time queue runner runs no matter what data size of the job is.
=> Always process at least one queue job

etc/module.xml
This fix solve problem with multiple critical errors in support_report.log
```
[2017-04-26 09:53:45] report.CRITICAL: Broken reference: the 'algolia.beforecontent' element cannot be added as child to 'main.content', because the latter doesn't exist [] []
[2017-04-26 09:53:45] report.CRITICAL: Broken reference: the 'algolia.autocomplete.product' element cannot be added as child to 'before.body.end', because the latter doesn't exist [] []
[2017-04-26 09:53:45] report.CRITICAL: Broken reference: the 'algolia.autocomplete.category' element cannot be added as child to 'before.body.end', because the latter doesn't exist [] []
[2017-04-26 09:53:45] report.CRITICAL: Broken reference: the 'algolia.autocomplete.page' element cannot be added as child to 'before.body.end', because the latter doesn't …
```
=> Fix Critical errors: Broken reference

view/frontend/web/internals/algoliasearch.css
The fix was very small in the end. Width for `.col9` and `.col3` is already defined and the lines just below override the default style for mobile (see `#algolia-autocomplete-container.reverse`).
Relates to #215
=> Fix responsive style for wider screens

Helper/ConfigHelper.php, Helper/Entity/ProductHelper.php, Helper/Image.php, etc/adminhtml/system.xml
Fix #214
The problem occurs when you set the `/pub` directory as the server root directory. Because Algolia indexer runs in command line there is no way to know if the server serve request from `index.php` or `pub/index.php`.
The best way to set your server to ignore `/pub/` in URLs but for all the user that can change their server configuration, they can turn on this option. Full reindex is required after this option is modified.
Added FAQ entry here: https://github.com/algolia/magento/pull/49
=> Fix thumbnail URL when using /pub/ dir as the root dir

Model/Queue.php
When the full queue is being processed, this function recurses after
handling a set of jobs - so we need to quit when we run out of jobs to
process.
This resolves GH-285
For comparison, the M1 module implements this as: https://github.com/algolia/algoliasearch-magento/blame/a0200a39403dd13e0f4820e325e772f985bcccbc/app/code/community/Algolia/Algoliasearch/Model/Queue.php#L77-L79
=> Prevent infinite recursion when EMPTY_QUEUE=1

view/frontend/web/instantsearch.js
Fix #288 
Today, with Instant Search activated,  Algolia is called and the DOM is updated on every page. This PR will only call algolia if you type something is the search bar or if you're on a result page (like category).
It could be nice to add some tests but I haven't really figured out how.
=> Do not call API on non product page

etc/adminhtml/system.xml
Move Algolia config menu tab from sortOrder="10" (before General config) after Services tab. Adding new menu entries before the General config is not considered as best practise in Magento.
=> Move Algolia config menu tab

Helper/Entity/ProductHelper.php
Reproduce:
Observer for `algolia_product_index_before`:
```
public function execute(\Magento\Framework\Event\Observer $observer)
{
/** @var \Magento\Catalog\Model\Product $product */
$product = $observer->getProduct();
$data = $observer->getCustomData();
$data->setData('in_stock', 1);
$observer->setCustomData($data);
}
```
=> Fix error when in_stock comes from $defaultData

Helper/Data.php
Good day,
In situation when configurable product is set "In stock" but all its simple variations have qty 0, this product in fact shows as not available on frontend and shouldn't go to Algolia. I changed the check to isSaleable.
Please review :)
=> Hide out of stock for configurable products

Block/Algolia.php, Block/Instant/Hit.php
In order to avoid cache issues it's better to use `Magento\Customer\Model\Context` instead `Magento\Customer\Model\Session` to get customer group id
=> Customer group id fix

Helper/Entity/ProductHelper.php
**Summary**
As it is now the product thumbnail image is hardcoded to 75x75 so if you want to display larger images on the autocomplete list the only choice is to use CSS but this will make images look blurry.
It would make sense to use the `product_thumbnail_image` image size here instead which is already 75x75 by default and, if anyone needs a different custom size, it can be overwritten using the `etc/view.xml` file.
**Result**
Notice image quality is increased after the image size change.
| Before | After |
| --- | --- |
| <img width="529" alt="screen shot 2018-03-22 at 10 42 18" src="https://user-images.githubusercontent.com/661330/37766071-c3f16362-2dbd-11e8-887b-5ad2a1739b6b.png"> | <img width="526" alt="screen shot 2018-03-22 at 10 40 28" …
=> Make product thumbnail configurable

view/frontend/web/internals/common.js
This resolves an issue with Add to cart on instant search page - first time.
After login the window reloads and the cookie `form_key` gets updated but Algolia keeps old value until another window reload occurs.
This fix just compares Algolia `form_key` value with the cookie one, if they differ it updates Algolia to the cookie one.
=> Resolve issue Add to cart on instant search page - first time.

Model/Observer.php
The prevent backend rendering functionality is only needed for category pages, so when there is no current_category from the registry the observer can return.
**Summary**
I found that the sidebar in the account pages in magento 2 where missing, caused by this bug.
**Result**
Sidebar will only be removed on category pages and if the algolia prevent backend settings apply
=> Prevent backend rendering only for category pages

Model/Source/ImageType.php
When setting 'small image' as the image type for the images used in Algolia, we noticed base image was used. When changing the value in the database to `product_small_image` instead of `small_image`, it worked like we wanted.
Reference for image type ID's can be found in Magento core; `vendor/magento/theme-frontend-blank/etc/view.xml`
=> Set correct type IDs for image type selector in configuration

Helper/Entity/Product/PriceManager.php
We were experiencing a number of products having a price of 0 (zero) in the category pages but not on the product pages. After debugging with xdebug, I've found the comparison operator in PriceManager to be the culprit;
```
if ($customData[$field][$currencyCode]['default'] === 0) {
$customData = $this->handleZeroDefaultPrice(
$customData,
$field,
$currencyCode,
$baseCurrencyCode,
$min,
$max,
$store
);
}
```
This checks for a zero default value by `===`. But PHP's `round()` function returns a float, and not an int. Changing this to `==` loosens the comparison and fixes the issue.
=> Change comparison operator to == instead of === for nonzerodefault price

Helper/ConfigHelper.php
**Summary**
We noticed the prevent backend rendering functionality did not work correctly; the pages for the Googlebot did not include the HTML of Magento's category listing. We found that it was due to a `\r\n` being present in the `algoliasearch_advanced/advanced/backend_rendering_allowed_user_agents`  value. Probably due to somebody on Windows editing that text. The code only split on `\n`, thereby getting `Googlebot\r` and `Bingbot` as a result. `Googlebot\r` does not match in the user agent string `Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)` and there it *will* prevent backend rendering.
**Result**
Backend rendering is *not* prevented for Googlebot.
=> Fixed exploding of line breaks where \r\n was used instead of \n

view/adminhtml/templates/adminjs.phtml
**Summary**
Documentation links in the admin about setting up the indexing queue were linking to Magento 1 documentation.
**Result**
They now link to Magento 2 documentation.
=> Fix wrong urls to index queue documentation

view/frontend/web/instantsearch.js
**Summary**
On any list page first load, URL does not contain hash segments. Those are added after page load by JS.
This means, code to add hierarchicalFacetsRefinements in searchParameters is executed, which is fine.
Problem is it overwrites parameters set above in instantsearchOptions initialization code e.g. hitsPerPage
**Result**
Result is, for first load, request to Algolia does not contain hitsPerPage parameter and default number of records are loaded i.e. 20 even if you have set 100 in the extension backend
=> hitsPerPage gets overwritten for first load fixed

view/frontend/web/internals/common.js
**Summary**
In https://github.com/algolia/algoliasearch-magento-2/blob/d7482b561eb2f3fe41867c83fef130fd08f8c728/view/frontend/templates/instant/wrapper.phtml ...
```
<div id="refine-toggle" class="visible-xs visible-sm">
+ <?php echo $block->escapeHtml(__('Refine')); ?>
</div>
```
It is line terminator characters that is obtained from the above elements using `$(this).html()[0]`.
If we try to get the string "+" or "-", we need to get rid of the obstacles first.
**Result**
Replacement of "+" and "-" is correct.
=> Fixed incorrect replacement of "+" and "-" of toggle button of facet panel when displayed on small screen

Helper/Entity/CategoryHelper.php
Here you are converting entity_id to row_id if customer is using Magento EE and version is greater than 2.1.0 but lots of customer may not use staging modules which actually changes entity_id to row_id.
Like we are using dumpautoload to remove all staging modules. I have just added a check if Magento_Staging module is in play. Because all staging modules are dependent on this one. So if this one exists then we can convert entity_id to row_id. Else we wont.
**Summary**
**Result**
=> Check if staging modules are being used

Controller/Adminhtml/System/Config/Save.php, etc/adminhtml/di.xml
Fix deactivated serialized arrays : when IS or autocomplete are turned off in the Magento configuration, prevent serialized array fields to be emptied.
=> Fix deactivated serialized arrays

Helper/AlgoliaHelper.php
**Summary**
We have extremely large configurable products (up to 10.000 SKUs). When syncing these products to Algolia, we noticed that these products were being skipped, like this;
```
Algolia reindexing: 
You have some records which are too big to be indexed in Algolia. 
They have either been truncated 
(removed attributes: description, short_description, meta_description, content) 
or skipped completely: 
magento2_st_de_products 
- ID 692545 - skipped - longest attribute: sku
```
This turns out to be because the `sku` attribute in the object is filled with all the child SKU's of the configurable products. This makes sense; it makes the configurable product discoverable through any of its child SKUs. However, in our case, we have thousands of these SKU's and there is a slim chance anyone …
=> Truncate sku field for large configurable products when handling large objects

Block/Adminhtml/BaseAdminTemplate.php, Factory/ViewModelFactory.php, ViewModel/Adminhtml/Analytics/Form.php, ViewModel/Adminhtml/Analytics/Overview.php, ViewModel/Adminhtml/BackendView.php, ViewModel/Adminhtml/Support/Contact.php, ViewModel/Adminhtml/Support/Overview.php, view/adminhtml/layout/algolia_algoliasearch_analytics_index.xml, view/adminhtml/layout/algolia_algoliasearch_support_contact.xml, view/adminhtml/layout/algolia_algoliasearch_support_index.xml, view/adminhtml/templates/analytics/form.phtml, view/adminhtml/templates/analytics/graph.phtml, view/adminhtml/templates/analytics/overview.phtml, view/adminhtml/templates/support/components/legacy-version.phtml, view/adminhtml/templates/support/contact.phtml, view/adminhtml/templates/support/overview.phtml
Magento 2.2 suggests [to use ViewModels instead of inheriting Magento's template class](https://firegento.com/blog/2017/12/07/better-blocks-magento-2-php-view-models/) (thank you @damcou for spotting that).
However, this approach is not backward compatible with Magento 2.1.
This PR "hacks" Magento 2.1 and gives templates ability to load ViewModels via the same method, but with [a BaseTemplate and it's Factory as dependency](https://www.yireo.com/blog/2017-08-12-viewmodels-in-magento-2) (thank you @bsuravech for finding this solution).
It's not the best solution for Magento 2.2 and higher, but will give us the best (easiest) solution for the future when we decide to drop support of Magento 2.1 and rely only on ViewModels.
Could you please review and let me know what you think, @bsuravech …
=> Refactor templates to use ViewModel factory to support M2.1

view/frontend/web/autocomplete.js, view/frontend/web/internals/common.js
Fix the beforeAutocompleteSources frontend hook for autocomplete (allows to complete the tutorial [How to add external autocomplete source ](https://community.algolia.com/magento/doc/m1/external-autocomplete-source/) )
=> Fix autocomplete frontend hook

etc/mview.xml
Hi there, how is it going?
Our customers too often complain that when they start new campaign with catalog rules, Algolia prices are not updated, and ask us to reindex all manually. That's it! We need to do something about it :)
One difficulty with catalog rules is that it's sometimes difficult to know when some particulat product is affected by catalog rule. After some research I found that after catalog rules reindex, catalog price index is always called. This means that we can subscribe to `catalog_product_index_price` table and get Algolia to reindex when new rules take effect.
We keep all our indexers in update by schedule mode and Algolia queue runner enabled, so this approach should work.
1. Let's test on simple products, default Magento 2.2.7. Bag initial price 45 NOK. …
=> Subscribe to price index changes - reindex products when catalog rule is applied

composer.json
**Summary**
https://discourse.algolia.com/t/magento-2-error-after-upgrading-module/7059/3
Need to update minimal version of the algoliasearch-client-php to 1.27 to include Analytics class for our analytics features. 
**Result**
- Updated minimal version in composer.json
=> update minimal version to 1.27 for analytics dependency

Helper/Data.php, Setup/UpgradeSchema.php, Test/Integration/QueueTest.php, etc/adminhtml/system.xml, view/adminhtml/templates/common.phtml
Each job to run has overhead with fetching data from database. 
Making it run less jobs (10 -> 5) with bigger page size (100 -> 300) reduces the overhead and improves the indexing performance, especially for simple products.
=> Optimize default indexing queue settings

view/frontend/web/internals/common.js
**Summary**
Support Ticket #117914 
There is an issue in M2.1 when javascript is minified and common.js is throwing a syntax error. This is because M2.1's JShrink\Minifier does not consider backtick template literals a string type and thinks the // in the template literal, still a comment line. This is corrected in M2.2. 
https://github.com/algolia/algoliasearch-magento-2/blob/master/view/frontend/web/internals/common.js#L569-L571
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
**Result**
- Updated return string type to be accepted in 2.1
=> M2.1 JS Minify Issue

Setup/UpgradeSchema.php
**Summary**
Support Ticket #118627
Autocomplete missing product_count value from response. Recommended to add product_count as a retrievable attribute. Should be added by default to the configuration. 
**Result**
- Added product_count to the UpgradeSchema to match what is added when added manually
=> Add product_count to Categories additional attributes default

view/frontend/layout/algolia_search_handle.xml, view/frontend/web/internals/common.js
**Summary**
IE11 has some issues with ES6 syntaxes for method definition shorthand and destructuring assignments. You can read more about it here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
Related Issues: #677, #659 
**Result**
Converted syntax into IE11 friendly versions. Manually assigning variables instead of the shorthand.
=> Update JS for IE11 compatibility 

view/frontend/layout/algolia_search_handle.xml, view/frontend/templates/internals/configuration.phtml
**Summary**
Add crossorigin attribute to prevent CORS.
**Result**
Magento threw an error for crossorigin as an attribute for <script>. I had to move it to the configuration.phtml file to add that parameter.
=> Fix IE11 polyfill crossorigin attribute

Block/Adminhtml/Queue/Status.php, README.md, etc/adminhtml/system.xml, view/adminhtml/templates/analytics/overview.phtml, view/adminhtml/templates/catalog/category/edit/merchandising.phtml, view/adminhtml/templates/common.phtml, view/adminhtml/templates/support/components/legacy-version.phtml, view/adminhtml/templates/support/overview.phtml, view/adminhtml/web/js/support.js, view/frontend/web/autocomplete.js
We moved Magento documentation from it's [community website](https://community.algolia.com/magento/) to [official Algolia's documentation](https://www.algolia.com/doc/integration/magento-2/getting-started/quick-start/).
The legacy links are redirected, but it's better to link directly to new documentation pages. This commit changes the links.
=> Update docs links to lead to new documentation

Controller/Adminhtml/Analytics/Update.php
**Summary**
Bug reported internally by @AlexEven. The Update Action was pulling the old class before we switched over to using View_Model classes via block factory.
**Result**
This has been updated to the correct block class and view_model in the Update action file.
=> Fix Analytic Overview Update Action

Model/Indexer/Category.php, Model/Indexer/Product.php, Model/Queue.php, Setup/Uninstall.php, Setup/UpgradeSchema.php, Test/Integration/QueueTest.php
- Jobs are now split into 2 types - realtime and full reindex
- Realtime jobs have higher priority and will be processed before full reindex queue
- At least 1/3 of processed jobs will be jobs of full-reindex
- Removed raw SQL queries
- Added PHP doc annotations
- Slightly better readability
TODO:
=> Refactored Queue mechanism

Helper/Data.php
**Summary**
$collection->getAllIds() unsets the select query and retrieves the entire collection IDs. For the getSalesData() method, we should filter the collection IDs down to the current page and limit in the query. Use getColumnValues() to retrieve all entity_ids of the queried product collection.
**Result**
Optimized select query for getSalesData();
=> Sales Data - change getAllIds() to getColumnValues() for optimization

view/adminhtml/ui_component/algolia_algoliasearch_indexing_queue_listing.xml
**Summary**
For troubleshooting, it might be helpful to have a button to export the indexing queue table so that the client can send over upon request for those who do not have DB access.
**Result**
Added a button to the indexing queue page.
=> Indexing Queue export button

view/frontend/web/click_conversion_analytics.js, view/frontend/web/instantsearch.js
**Summary**
A helpful suggestion from our community with regards to our instantsearch hooks to allow the ability to use instant search connectors via the algoliaBundle 
Related issue: #724
**Result**
Additional parameter for instantsearch hooks for algoliaBundle.
=> Add algoliaBundle to Instantsearch hooks

Helper/Entity/Product/PriceManager/ProductWithChildren.php
**Summary**
[MAG-136] Customer group pricing on grouped products are returning 0 instead of min/max values. 
Related issue: #668 
**Result**
Cast type on group price for type comparison in setFinalGroupPrices();
[MAG-136]: https://algolia.atlassian.net/browse/MAG-136
=> Fix customer group prices on grouped products

Helper/Image.php
**Summary**
[MAG-137] Reported bug. Even though product image type is specified it is still using the base image even for thumbnail.
Related Issues: #643 
**Result**
\Algolia\AlgoliaSearch\Helper\Image::initBaseFile() is a rewritten method from \Magento\Catalog\Helper\Image. I removed it since it was setting all images to getImage() [base image] instead of the specified type. That was the only purpose of this method so I removed it to revert to default behaviour. 
[MAG-137]: https://algolia.atlassian.net/browse/MAG-137
=> Bugfix product image only pull base and not type

Helper/Data.php, Helper/Entity/CategoryHelper.php
**Summary**
[MAG-138] Page emulation does not stop on exception error and will persist into other indexing operations. 
Related Issues: #613
**Result**
Relocate emulation functions around getPages and add try/catch debugging for issues related to CMS pages on addObjects. Also threw in a spacing fix that was bothering me. 
[MAG-138]: https://algolia.atlassian.net/browse/MAG-138
=> Indexing pages stop emulation on error

Controller/Adminhtml/Reindex/Save.php
**Summary**
Update addErrorMessage() in \Algolia\AlgoliaSearch\Controller\Adminhtml\Reindex\Save to remove exception object in parameters. 
Related Issues: #748
**Result**
Updated all addErrorMessage calls in Reindex SKU save controller.
=> remove exception object from parameter for addErrorMessage method

Helper/Entity/ProductHelper.php
**Summary**
Helpscout Issue (132804) reported searchable attributes are not respecting scope level and only returning default or current saved. 
**Result**
Added storeID for searchableAttribute so that it pulls correctly the scope.
=> Bugfix searchable attribute configuration not saving correct scope 

Helper/AlgoliaHelper.php, Helper/ConfigHelper.php, Model/Source/MaxRecordSize.php, etc/adminhtml/system.xml
**Summary**
[MAG-132] Create a configuration for max_record_size with default size to 10000 and dynamic value added from plan. 
**Result**
Truncate data when necessary according to plan size to reduce "Record is too big" errors and reduce batch indexing process errors. 
[MAG-132]: https://algolia.atlassian.net/browse/MAG-132
=> Add Max Record Size Limit 

Model/Indexer/CategoryObserver.php
Improving PR #759
Following best practice in Magento to avoid using around for plugin by changing to the appropriate before/after method. 
Previous aroundDelete getProductCollection() was not fetching the correct store view product collection for category and in some cases not returning any products. Since we only require product_ids, I used the getProductsPosition() to fetch the product IDs to be passed into the $affectedProductIds variable for indexing.
=> Update Category Plugin 

Helper/AlgoliaHelper.php, Helper/Data.php, Helper/Entity/ProductHelper.php, Model/IndexMover.php, Model/Indexer/Product.php, Model/Queue.php, Model/Source/JobMethods.php, Test/Integration/QueueTest.php
**Merge settings from production index to TMP index**
Fixes issue when settings to TMP index were "merged" from non-existing TMP index. Therefore it reset the settings set on production index when TMP index was moved to production as those settings were never set there.
**Set settings to TMP index immediately before the move**
Fixes issue when settings were applied to a production index and full reindex process was in progress (TMP index was already existing). Those settings were not propagated to TMP index and during the move of TMP index, the settings were overridden.
=> Fix setSettings on TMP index

Block/Adminhtml/Category/Merchandising.php, view/adminhtml/templates/catalog/category/edit/merchandising.phtml, view/adminhtml/web/css/common.css, view/adminhtml/web/css/merchandising.css
**Summary**
- [MAG-181] Add Product Display warning for category pages if the display mode is set to CMS only
- [MAG-190] Add validation/limit to 50 on category merchandiser
- [MAG-180] Update top/bottom margins to Merchandising page
[MAG-181]: https://algolia.atlassian.net/browse/MAG-181
[MAG-190]: https://algolia.atlassian.net/browse/MAG-190
[MAG-180]: https://algolia.atlassian.net/browse/MAG-180
=> Update Category Merchandising 

Helper/Data.php
Fix the wrong base url used in the full category reindexing process when there are more than one store.
=> Add Store emulation for full category reindexing

etc/acl.xml
**Summary**
Add ACL for Algolia Search Configuration section for non administration users. 
**Result**
- ACL added for extension configuration. 
- Updated title text for menu ACL.
=> Add ACL for Algolia Search Configuration section

Model/Indexer/ProductObserver.php
**Summary**
Remove the isQueueActive() check for the product interceptor. This issue was raised in a historical PR by a community member, @peterjaap. Thanks! 
https://github.com/algolia/algoliasearch-magento-2/pull/783
**Result**
Removed condition and made sure that all interceptors for Product are running as expected for both Update on Schedule and Update on Save.
=> Update Product Interceptor Condition

Helper/Image.php
**Summary**
Configurable products without an image are not pulling from their child product image as it did before.
Related Issues: #818
**Result**
Add back the initBaseFile() method, however, fetching the appropriate image type from child products if the configurable parent does not have an image set.
=> Update get product images

Model/Indexer/CategoryObserver.php, Model/Observer/CategoryMoveAfter.php, etc/adminhtml/events.xml
**Summary**
Products within a category needs to be updated when a category name, include_in_menu, and/or is_active attributes are updated. When the algolia indexes are set to Update on Schedule, the mview subscription for categories does not push products into the algolia_products_cl table if a products in the category have not been changed. We need to compensate for this missing condition. 
Related Issues: #758
**Result**
Updated the CategoryObserver beforeSave() method to pass in also deleted or added products as well as condition the product collection to only when there are specific modifications. This is to reduce extra operations on indexing. We also added a new method to update the product depending on the mode of the indexer.
=> Category Product Updates for Update on Schedule

.circleci/config.yml
**Summary**
Remove Magento 2.1 version check from Circle CI jobs. 
**Result** 
Testing for PR should now only run 2.2 and 2.3 checks.
=> Remove CircleCI job for Magento 2.1 check

.circleci/config.yml, composer.json
Adds a job to test if we're not using PHP in ways that could not work in [versions supported by Magento](https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html#php).
=> chore: making PHPCompatibility assess no funky <7.1 PHP is used in our project

.gitignore
This pull request adds `/.php_cs.cache` under gitignore.
=> chore: adds `/.php_cs.cache` under gitignore

dev/cloud/setup.sh, dev/cloud/teardown.php, dev/cloud/teardown.sh
**INTERNAL DEV ONLY** 
Scripts to run for setting up and tearing down algoliasearch in the development Magento Commerce Cloud environment. This sets the environment prefix to the environment variable `MAGENTO_CLOUD_ENVIRONMENT` that is provided by the cloud. The teardown script will remove indexes and its replicas in a double iteration.
=> Magento Cloud Development setup teardown

Helper/Data.php
**Summary**
Hi! We came upon a problem with custom uploaded image placeholders in different store views - their configuration is not visible for stores other than first.
Steps to reproduce:
1. Add a product without an image
2. Go to Stores > Configuration > Catalog > Catalog
3. Switch scope to **non-default store view** (e.g. second in the list)
4. Upload custom images in _Product Image Placeholders_ section
5. Reindex Algolia, e.g. single product by SKU - Stores > Algolia > Reindex SKU
Expected: _custom_ image placeholder in Algolia search for this product.
Actual: _default_ image placeholder.
After debug, problem is in [ScopeCodeResolver](https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/App/Config/ScopeCodeResolver.php#L43). 
1. Algolia iterates …
=> Clean scope code resolver when starting environment emulation

Helper/Entity/CategoryHelper.php
**Summary**
When working with a multi-store-view application, I found that the default request path (from the `url_rewrite`) table was selected. This caused the `request_path` from the default store to be loaded instead of the one associated with the current store.
*Before:*
**Result**
=> Fixing order of setting parameters

view/frontend/templates/autocomplete/category.phtml, view/frontend/templates/autocomplete/product.phtml, view/frontend/templates/instant/hit.phtml
**Summary**
ALT attribute is missed on Algolia Search page or Category page. 
**Result**
ALT attribute has been added in Hit template and for categories and images in autocomplete menu.
=> Added alt attribute for img tags

Helper/Entity/ProductHelper.php
**Summary**
Algolia shoud create replicas if backend facet rendering is enabled, otherwise it raises errors when we try to sort because replicas do not exist.
=> Create replicas if Backend Facet Rendering is enabled

Setup/UpgradeSchema.php, etc/module.xml
**Summary**
Migration isn't applied for installed version 1.12.0 and fix won't be worked after upgrade to 1.12.1 or higher. 
**Result**
Changed version for migration to 1.12.1 ( the same version as set in PR`s milestone field)
=> Fix version to 1.12.1 for unsubscribe Mview migration (PR #870)

Helper/Entity/ProductHelper.php
**Summary**
After 1.12.0 and PR #841  Issue is back. Configurable product is set "In stock" but all its simple variations have qty 0, this product in fact shows as not available on frontend and shouldn't go to Algolia.
**Result**
Applied fix from #378 to new method productIsInStock.
PR is created for 1.x branches, but Fix is actual for 2.0 too.
=> Hide out of stock for configurable products (move PR #378)

etc/adminhtml/system.xml
Makes the "replace categories" configuration independant from instantsearch enablement
=> Quickfix - Replace categories configuration 

Helper/ConfigHelper.php, Model/Queue.php, Setup/UpgradeSchema.php, etc/adminhtml/system.xml
Added a logic which clears the archive logs (from algoliasearch_queue_archive) older than 30 days.
=> Archive logs cleaning

Api/Data/RunInterface.php, Controller/Adminhtml/Queue/Log.php, Model/ResourceModel/Run.php, Model/ResourceModel/Run/Collection.php, Model/ResourceModel/Run/Grid/Collection.php, Model/Run.php, etc/di.xml, view/adminhtml/layout/algolia_algoliasearch_queue_log.xml, view/adminhtml/ui_component/algolia_algoliasearch_indexing_log_listing.xml, view/adminhtml/ui_component/algolia_algoliasearch_indexing_queue_listing.xml
Added :
- Button "See Run logs" on the Algoliasearch queue overview page that leads to the new queue log grid
- "Queue log grid" that contains a grid populated by the algoliaseach_queue_log table (filterable by data and by run id)
=> Adding Queue log grid

Helper/Entity/AdditionalSectionHelper.php, Helper/Entity/PageHelper.php, Helper/Entity/SuggestionHelper.php
Hi!
It's continue from PR #495 and remove ObjectManager use in Pages, Suggestions and Additional sections entity helpers. In addition, It's part of  PR #936 and remove literal class names from model.
Thnx!
=> Remove Object manager and add factories to constructor

Helper/Entity/ProductHelper.php
Add indexOutOfStockOptions() behaviour (defined by **"Stores -> Configuration -> Algolia Search -> Products: Index out of stock options for configurable products"** ) which has been previously removed during the helper refactoring.
Now, you can have out of stock simple products indexed and out of stock configurable options not indexed (see issue https://github.com/algolia/algoliasearch-magento-2/issues/951 )
=> Add forgotten indexOutOfStockOptions() method behaviour

Helper/AlgoliaHelper.php
PHP v2 Client Update taskID array key warning. Added condition to prevent warning.
=> Fix warning on missing taskID array key

Helper/Image.php
Taken from @gibbotronic's suggestion regarding configured configurable product images being overwritten by child product image. This is to correct it so that. 
Related Issues: #962
=> Fix configurable image condition

Helper/Entity/ProductHelper.php
Bundle products were reported to not have child SKUs indexed. This was originally pulling the option types for the selections instead of the selections products themselves. 
HS Ticket # 231950
=> Fix bundle product selections for subproducts

Model/Observer/CleanCatalogImagesCacheAfter.php, etc/adminhtml/events.xml
After a user has flushed image cache, image links that have been indexed will not work causing broken image links. Due to performance, we have chosen not to perform an automatic full reindex of their catalog indexes but to throw a warning message after the event has fired. 
HS Ticket #232908
=> Add warning after image cache is flushed

Helper/Entity/ProductHelper.php
Fixes a small issue while deletion of index's QR (the PHP client V2 expects an array for the RequestOptions parameter)
=> Fix ProductHelper's clearFacetsQueryRules() method

.circleci/config.yml
The current circle ci config was assuming that: if the `{extension}/composer.json` do not change, the global vendor should be the same. And that is not true.
The pull request makes the global vendor always start from a clean state.
=> chore(ci): do not use cache on the global composer vendor

etc/adminhtml/system.xml, view/frontend/web/internals/common.js
For conversion tracking for CC Analytics, we now append URL parameters to searched results. This update is to add a description explaining this change and to recommend they enable the canonical links for product settings in Magento.  
Additionally, I added an extra condition so that the insights URL params should only be added if conversion mode has been set.
=> Update CC Analytics description for insights parameters 

Helper/ConfigHelper.php
Fixes https://github.com/algolia/algoliasearch-magento-2/issues/1024
=> Prevent division by zero in the Notice Helper when configuration is not set

Helper/AlgoliaHelper.php
Fix for PHP Client v 1.27.0 to use `scopedCopyIndex()`  for query rules.
Related to #1029
=> Fix query rules empty array by using scopedCopyIndex method

.circleci/config.yml
For safety to mitigate issues with updates.
=> Remove composer self-update from circleCI quality tools

view/frontend/web/internals/autocomplete.css
**Summary**
grid.css is being included a second time redundantly. 
Also, when Magento has "Minify CSS" enabled, an error occurs because "./grid.css" doesn't exists in the deployed files
---
In the future it would be a good idea to include the css using the _module.less method, so it's available for automatic bundling/minification, and maybe extension and theming
=> Remove extra grid.css import

Model/IndexMover.php
**Summary**
Conditions:
* The queue is enabled
* Indexing is disabled on global
* Indexing is enabled on one store/website
In that case, the data for products will never be promoted from _tmp to the index.
The problem is that the queued job is not checking against the $storeId passed with the data and so it's checking against default. It works without the queue because in that case there is current store emulation.
=> Queue doesn't update products unless enabled globally

Helper/InsightsHelper.php
HS Ticket: # 271958
To address this error message:
```
[2020-07-06 10:10:55] main.CRITICAL: UserToken must contain only alphanumeric, hyphen, or underscore characters, and be between 1 and 64 characters long {"exception":"[object] (Algolia\\AlgoliaSearch\\Exceptions\\BadRequestException(code: 422): UserToken must contain only alphanumeric, hyphen, or underscore characters, and be between 1 and 64 characters long at /var/www/www.clarosa.fr/web/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:210)"} []
```
=> Update setUserToken to cap character length

Helper/AlgoliaHelper.php
For 1.x version. Do not forward query rules to replicas. 
HS Ticket #268254
=> Set forwardToReplicas for copy rules to false

view/frontend/web/instantsearch.js, view/frontend/web/internals/autocomplete.css
In version 2.x, we upgrade instantsearch library from v2 -> v4. With this upgrade, the functionality of the searchBox widget has changed to only accept a container instead of using your own input field has it did before. This change was documented here:
https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/js/#searchbox
With @eunjae-lee, we were able to restore this dropped feature by creating a customSearchBox.
HS Ticket: #271451
=> Restore "search as you type" feature for v2

Helper/Entity/PageHelper.php
**Summary**
* Set store scope using correct function to avoid using Default store domain
* Get a clean UrlInterface instance to avoid problem where domain from previous store in the loop is used.
=> Fix error on URL during Pages indexing

Helper/Entity/ProductHelper.php
**Summary**
While creating the replicas for sorting, the setting read is not correctly scoped and it can fail depending on other stores configuration.
=> Use current store id to get settings for replicas

Helper/Entity/Product/PriceManager/Bundle.php, Helper/Entity/Product/PriceManager/ProductWithChildren.php
**Summary**
When indexing configurables, the Original / Discount relationship is lost, This saves the original prices to have the discount visible
=> make sure original price range is saved for configurables

Block/Instant/Hit.php, Helper/ConfigHelper.php, Helper/Entity/Product/PriceManager/ProductWithChildren.php, view/frontend/templates/instant/hit.phtml
This PR fixes invalid values on the price metadata (price and currency should be separated and unformatted).
It also changes:
* separate Offer from AggregateOffer, for products with a single price or a range. Also, highPrice should not be used for price without discount (for that you need to create different offers with different validity dates or conditions)
* add required fields from Google analysis tool:
* Proper formatting of ListItem (Product should be a child of it)
* ListItem.position
* Product.url
A different PR is needed to fix the correctness of the rest of the html, since `<button>` can't be a child of `<a>`
=> Fix microdata on instantsearch

view/frontend/templates/internals/configuration.phtml
Having this condition here does more harm than good. Customers who have minified and strip HTML comments come across the algoliaBundle missing error often because of this script. 
Since we support IE 11 and higher, we should drop this.
=> remove less than IE9 condition from configuration template

view/frontend/web/instantsearch.js
HS Ticket: 284619
Category Filtering when facet is not configured was removed accidentally in favour for UiState of the category facet. We need to add back this line to add facetParameters when facet is not configured for categories:
https://github.com/algolia/algoliasearch-magento-2/blob/1.13.2/view/frontend/web/instantsearch.js#L103-L112
=> Instantsearch Category Filter when category facet is not configured

view/adminhtml/layout/algolia_algoliasearch_queue_log.xml, view/adminhtml/templates/queue/log/helper.phtml, view/adminhtml/templates/queue/status.phtml, view/adminhtml/web/css/common.css
To help with the support initiatives to improve how to read indexing queue logs to guide customers on optimising their indexing queue.
=> Add messaging for indexing queue and logs

Model/Job.php
HS Ticket: 283569
Pages are getting cached, but are getting uncached after some minutes, without any change due to the indexing queue cache tags. Identity class needs to be removed from the Indexing Queue Job entity as it is mostly static and not used for customer facing display: 
https://devdocs.magento.com/guides/v2.4/graphql/develop/identity-class.html
=> Remove IdentityInterface from Indexing Queue Job model class

view/frontend/web/instantsearch.js
JIRA Ticket: [MAGE-48] exclude category facets from clearRefinement on category page
HS Ticket: #289608
Test Cases:
/category
- enable category facet for instantsearch and instantsearch on category pages
- go to any category page
- filter on another attribute like color
- hit clear all 
Expected result is that category filter should not be removed from clearRefinment action on category pages. 
/catalogsearch/results
- enable category facet for instantsearch
- go to search results page
- filter on another attribute like color
- hit clear all 
Expected result should clear all filters including category filter
[MAGE-48]: https://algolia.atlassian.net/browse/MAGE-48
=> Exclude category facet from clearRefinement on category pages

etc/acl.xml
Hi!
It's available since Magento 2.1.3 and translate ACL resource label in the tree to selected Admin locale. For ex, for Norwegain "Algolia søk", or "Algolia" for another locales.
ofc, It'll be great to port this thing to 2.0.x version too.
Please review,
=> Set  ACL resource titles are translatable.

Model/Observer/Insights/CheckoutOnepageControllerSuccessAction.php
HS Ticket: 292821
If `$order` is not set by session, fall back to retrieve order from `order_ids`. 
This supports Magento 2 v2.2.x.
=> Update Personalisation Order Conversion 

Helper/MerchandisingHelper.php
[MAGE-63] Add rules tag for visual editor on Query Merchandising and Landing Page Builder features
This will allow the usage of the Visual Editor, if added to customer plan. Adding the visual editor tag will not effect rules for customers who do not have the Visual Editor enabled. 
**NOTE:**
Customers should know that if you edit the rule in the Algolia Dashboard, advanced options other than promote are not supported in the extension. Editing the rule in Magento will override changes in made in Algolia. Adding advance options means that the rule should only be edited in Algolia moving forward. 
[MAGE-63]: https://algolia.atlassian.net/browse/MAGE-63
=> Add tags for merchandising queries to use VM if applicable

view/frontend/web/instantsearch.js
Community member identified that the showMoreLabel was updated in ISv4 to templates.showMoreText. This has been corrected. 
https://discourse.algolia.com/t/showmorelabel-not-translatable-since-instantsearch-v3-magento-2/11337
=> infiniteHits update showMoreLabel to showMoreText

Model/Observer/Insights/CheckoutCartProductAddBefore.php, view/frontend/web/insights/add-to-cart-mixin.js
- Set the queryId value on product if add to cart form contains a queryID value. 
- Add to cart mixin should always add queryID for both add to cart and place order conversion.
=> Insights Analytics - Fix Add to Cart Conversion

composer.json
The ES compatibility module was experimental. Currently is not compatible for ES7 adapter. Will add back when it's updated at some point. For now, we will remove it.
=> Remove ES compat from suggestions

Helper/Entity/CategoryHelper.php, Helper/Entity/ProductHelper.php, Helper/Image.php, Test/Integration/ProductsIndexingTest.php
**Summary**
`removeProtocol()` should not be required. This was introduced in 2017 when both HTTP & HTTPS were in general use. Nowadays, only HTTPS is in general use for ecommerce websites. Browsers will typically display passive mixed content such
as images. If websites are having trouble with mixed content this will not be only because of Algolia search.
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content
See also #211
`removeDoubleSlashes()` is introducing a bug: a URL which is a full path only is having an additional slash added to the start, producing a valid-but-wrong URL. For example, '/media//wysiwyg//search.png' becomes '//media/wysiwyg/search.png'. Browsers cope just fine with URLs containing multiple slashes, so no …
=> Remove image URL manipulation

view/adminhtml/layout/algolia_algoliasearch_landingpage_edit.xml
Added missing handle for cms editor layout needed for pagebuilder.
As you can see in: vendor/magento/module-page-builder/view/adminhtml/layout/editor.xml
```
<referenceContainer name="before.body.end">
<uiComponent name="pagebuilder_modal_form" />
</referenceContainer>
```
We are missing the modal form at the bottom for the UI to toggle the aside editor. 
Solution was to add update handle to the LPB layout:
```
<update handle="editor"/>
```
This is tested in commerce and community 2.3
=> Fix Landing Page Builder feature wysiwyg/pagebuilder editor

view/frontend/web/internals/common.js
Add the ability to modify search options for autocomplete product source to allow ease of customisation. 
New event: `beforeAutocompleteProductSourceOptions`
=> Autocomplete add new hook for product source search options

view/frontend/web/internals/common.js
HS Ticket # 338995
Missing `__indexName` hit param for autocomplete sections: categories, suggestions, and additional sections indexes. This corrects the insights error on those items for click analytics.
=> Fix insights missing indexName for autocomplete sections

Helper/Entity/CategoryHelper.php
Prevents a bug related to confusion between row_id and entity_id in case category isn't fetched (can happen if it's a root category) #337360
=> Add small change on category indexing for Enterprise Edition

Helper/ConfigHelper.php
If customer groups are enabled, the generatedAPI key filters need to include the attributes for autocomplete indexes as well. 
We shouldn't have the same generatedAPIKey for all datasets in autocomplete so this is a quickfix and needs to be evaluated later.
=> Add additional attributes for customer groups 

Api/Data/JobInterface.php, Model/Job.php
**Summary**
Add set/get methods to job class. We need this methods in order to use entity in API and Magento queue.
I've chosen to use `body` instead of `data` since `data` is already use in the global `getData()`/`setData()` methods.
**Result**
Able to use job instance in API and Magento queue.
=> Add get/set methods for job instance

Helper/Entity/CategoryHelper.php
Patch to restore caching on category name lookup (scoped by store) to fix sloness in indexing as part of 3.10.0
HOTFIX FOR 3.10.0
=> HOTFIX FOR 3.10.0 - INTEG-492: Add category lookup cache by store scope

Block/Configuration.php, view/frontend/web/autocomplete.js, view/frontend/web/internals/template/autocomplete/additional-section.js, view/frontend/web/internals/template/autocomplete/categories.js, view/frontend/web/internals/template/autocomplete/pages.js, view/frontend/web/internals/template/autocomplete/products.js, view/frontend/web/internals/template/autocomplete/suggestions.js
**Summary**
This fixes translation issues with the 
- label for suggestions and categories and pages in autocomplete dropdown
- and 'no results' translation
=> bugfix: Fix for Translation in autocomplete (Ready to go)

Setup/Patch/Schema/AutocompleteConfigPatch.php
**Summary**
If a table prefix is configured, the AutocompliteConfigPatch will throw an Error because the table 'core_config_data' (without prefix) can't be found.
**Result**
After the Change, the AutocompliteConfigPatch can be applied if a table prefix ist configured.
=> Use getTable from ModuleDataSetupInterface to get table name with prefix

Helper/Entity/ProductHelper.php
**Summary**
In version 3.9.1, a fix was added for some storeview-related indexing issue. In this fix, it seems a bug fix was introduced, by removing the "!" in front of the `showCatsNotIncludedInNavigation` call:
https://github.com/algolia/algoliasearch-magento-2/commit/f1e3bb44def70f63ba203c1a252dde2811050c20#diff-c138874a1ad098fc3873ea690f53c7236c03b48cb63348e1049e11cc2392a2afL450-R451
As a result of this change, the `$filterNotIncludedCategories` variable in the `\Algolia\AlgoliaSearch\Helper\Entity\ProductHelper::getAllCategories` method is now `true` if the config "Show categories not included in navigation" is set to "Yes", and `false` if set to "No", instead of the other way around. That means that if the config is set to "Yes", which means categories that are not in the menu …
=> Fixed missing category data for products if show_cats_not_included_in_navigation is enabled

Helper/Data.php, Helper/Entity/ProductHelper.php, etc/indexer.xml
A dependency exists in `\Algolia\AlgoliaSearch\Helper\Entity\ProductHelper::getProductCollectionQuery` on the “Product Price” indexer (aka `catalog_product_price`) which performs a join on the underlying `catalog_product_index_price` table. 
Frequent catalog updates can create a detached state between this indexer and our `algolia_products` indexer. This affects both deltas and full reindexes - but is even more problematic for full indexes which can produce `_tmp` indices that are missing key products from a customer catalog. 
This PR aims to address this dependency when pushing data to Algolia to ensure that the pricing records are in place. 
Two items of note:
1. Assumes that the `catalog_product_price` index is in an invalid state before attempting the dependency reindex. To derive …
=> Fix/mage 604 - handle pricing dependencies

view/frontend/requirejs-config.js, view/frontend/templates/autocomplete.phtml
This PR is intended to address the bugs resulting from globally loading the Autocomplete library in non-applicable contexts - particularly checkout where the same global navigational elements do not exist.
=> Bugfix/mage 666 - conditional Autocomplete lib loading

view/frontend/templates/instant/facet.phtml
Use labels with `refinementList` to avoid presentation of JavaScript escaped values
=> MAGE-653 Use labels with refinementList 

view/adminhtml/layout/adminhtml_system_config_edit.xml, view/adminhtml/layout/algolia_algoliasearch_landingpage_edit.xml, view/adminhtml/layout/algolia_algoliasearch_landingpage_index.xml, view/adminhtml/layout/algolia_algoliasearch_query_edit.xml, view/adminhtml/layout/algolia_algoliasearch_query_index.xml, view/frontend/layout/algolia_search_handle.xml
Replace referenceBlock by referenceContainer following standard in adobe commerce / magento source code
**Summary**
According to adobe commerce / magento source code:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/view/base/page_layout/empty.xml#L13
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/view/base/page_layout/empty.xml#L20
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/view/adminhtml/page_layout/admin-1column.xml#L45
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Theme/view/adminhtml/page_layout/admin-2columns-left.xml#L48
The names "main.content" and "before.body.end" are containers and not blocks so it should use referenceContainer and not referenceBlock.
=> Replace referenceBlock by referenceContainer following standard in adobe commerce / magento source code

Helper/Entity/PageHelper.php
=> Fixed mb_convert_encoding() function deprecated issue in php8.2

etc/db_schema.xml
=> Increased character limit of Class in algoliasearch_queue

view/frontend/web/autocomplete.js
Previously we were not properly escaping special characters on the Autocomplete submit handler. This PR aims to remedy that.
=> MAGE-714 Handle ampersand and other special chars

Block/Configuration.php, Helper/ConfigHelper.php, etc/adminhtml/system.xml, etc/config.xml, view/frontend/web/autocomplete.js, view/frontend/web/internals/autocomplete.css
Provides an implementation for debouncing requests (configurable by milliseconds) as well as setting a minimal length for search terms before submission to the Algolia API.
Sample Autocomplete configuration:
=> Feature/mage 744 - debouncing autocomplete search requests

Helper/Entity/ProductHelper.php
This provides a critical fix for serialization of arrays that have been deduplicated leaving gaps in the key sequence. `json_encode` will serialize an array as a JSON object when the array keys are not consecutive. 
Because the scenario does not happen for every product only certain objects in the Algolia index may manifest this behavior. This can create a problem for Algolia features such as visual merchandising which require a scalar array to function as a category page ID and not an object and mixed data types can result in the index. 
Further details will be supplied in the corresponding Jira ticket.
=> Bugfix/mage 792 - categoryPageId serialization fix

view/frontend/web/instantsearch.js
An earlier merge conflict resolution incorrectly nested certain widgets. This PR restores custom banner functionality via the extension's Magento merchandising feature.
=> Bugfix/mage 796 - banner fix

.gitignore, Controller/Adminhtml/Landingpage/Delete.php, Controller/Adminhtml/Landingpage/Duplicate.php, Controller/Adminhtml/Landingpage/Save.php, Controller/Adminhtml/Query/Delete.php, Controller/Adminhtml/Query/Save.php, Helper/AdapterHelper.php, Helper/AlgoliaHelper.php, Helper/AnalyticsHelper.php, Helper/ConfigHelper.php, Helper/Data.php, Helper/Entity/AdditionalSectionHelper.php, Helper/Entity/CategoryHelper.php, Helper/Entity/PageHelper.php, Helper/Entity/ProductHelper.php, Helper/Entity/SuggestionHelper.php, Helper/MerchandisingHelper.php, Model/IndexMover.php, composer.json, view/frontend/web/instantsearch.js
This PR updates to Algolia PHP API client version 4 alpha. 
Some key changes include:
* New API namespacing
* New `AlgoliaAgent`
* `batch` API calls for both partial / full object updates and deletions
* Applied constants such as case sensitive `objectID`
* `getObjects` signature change
* `safeFetch` added to handle inconsistent return types in `AnalyticsHelper`
*  Wait tasks cleanup
* Fix secured API key call and adding `validUntil` to prevent long lived keys
* Reworked `copyRules` / `copySynonyms` to leverage core API 
* Fixed facet query rules for admin settings save
Caveats:
* `AnalyticsClient` v4 alpha is not yet generating proper endpoint paths. Current prefixing is incorrect per our [API documentation](https://www.algolia.com/doc/rest-api/analytics/#quick-reference-1).
=> Feature/mage 827 - PHP connector v4

Helper/Entity/Product/PriceManager/ProductWithoutChildren.php
**Summary**
The comma on the last item in the constructor is not allowed prior to PHP 8.0 and it's causing syntax issues. Check this for more information: https://php.watch/versions/8.0/trailing-comma-parameter-use-list
**Result**
This PR fixes the syntax error in the construct and make it backward-compatible.
=> [BUG] Fix for syntax error in construct

Helper/Configuration/NoticeHelper.php, view/adminhtml/web/js/config.js
Adds the following general notice to Magento admin pages to make it easier for customers to find their extension version:
=> MAGE-863 Add extension version notice

view/frontend/web/internals/template/autocomplete/categories.js, view/frontend/web/internals/template/autocomplete/pages.js, view/frontend/web/internals/template/autocomplete/products.js
**Summary**
There are certain index object attributes that the "out-of-the-box" integration expects to sync to Algolia to drive the default user experience. However, in the event that a customization is made, these configurations may be missing and additional checks are necessary. 
In this case, highlighting of attributes could fail if not found in either the `searchableAttributes` or `attributesToHighlight` configuration.
e.g.
Rather than be opinionated about which fields to include (by enforcing these values via code) this update allows graceful degradation. Further updates can be made through customization of the underlying JavaScript templates.
**Result**
The following screenshots demonstrate successful handling of the categories attribute...
With configuration:
Without configuration:
=> Bugfix/mage 889 - Autocomplete highlight robustness

Helper/AlgoliaHelper.php
Based on my limited knowledge, decompoundedAttributes setting is specific to Algolia dashboard. It should not be part of the merged settings. So I added in the remove list.
Now config saves without any error
=> MAGE-879: decompoundedAttributes removed from merging settings

view/frontend/web/instantsearch.js, view/frontend/web/internals/common.js
**Summary**
Errant decoding allows execution of arbitrary JS directly in the InstantSearch search box. This PR aims to refactor client side encoding / decoding in the `algolia` object and apply to the query before rendering on FE.
**Result**
Disallowed characters are escaped to HTML entities:
=> BUG: Client side encoding for front end XSS protection on InstantSearch search box

etc/adminhtml/system.xml, etc/config.xml
Admin config added for looking similar feature
=> MAGE-894: Looking similar admin config added

view/adminhtml/templates/job/view.phtml
**Summary**
Job view had a unnecessary opening tag, it breaks the page: "Data Size" label was not displayed.
**Result**
Job's "Data Size" label is displayed.
=> Removed unnecessary opening tag for DataSize field in job view

Model/Queue.php
**Summary**
If a queue has jobs from a full reindex, then some realtime jobs, and then another full reindex jobs, at the end the resulted index has less records.
**Details**
The issue is related to the way how jobs are loaded from the queue in \Algolia\AlgoliaSearch\Model\Queue::getJobs() method.
The jobs loaded from the queue to be processed by QueueRunner indexer consist of three parts:
- "full reindex" jobs - 33% of "max number of jobs per run"
- "realtime" jobs (from 33% up to 100%)
- rest are "full reindex" jobs (up to 100%).
The current logic of loading jobs from the queue is the following:
- step 1. loading 30% of "max number of jobs per run" of "full reindex" jobs (those with "is_full_reindex" = 1)
- step 2. loading "realtime" jobs (those with "is_full_reindex" = 0) - up to "max …
=> The index in Algolia after full reindex has less records than expected

Api/Product/ReplicaManagerInterface.php, Helper/Entity/ProductHelper.php, Model/IndicesConfigurator.php, Model/Product/ReplicaManager.php
This PR aims to ensure that replica changes propagate for all sorting attribute changes - including:
- changing virtual vs standard (update)
- changing sort direction (add + delete)
- updating ranking (relevant sort vs exhaustive sort)
- housekeeping to ensure that out of date replica indices are properly deleted
A new approach is taken to evaluating the change state between Algolia and Magento - relying on an opinionated prefix comparison vs comparing the old sorts that were previously used via backend model + ReplicaState. This is considerably less complex and requires less tracking of earlier states in Magento. It also allows sync state repair in the event of a failed operation on the Magento side of things where that change set could be lost.
=> Feature/mage 935 - handle toggle virtual / standard replica on individual attributes

Api/Product/ReplicaManagerInterface.php, Helper/ConfigHelper.php, Helper/Configuration/ConfigChecker.php, Helper/Entity/ProductHelper.php, Model/Backend/EnableCustomerGroups.php, Model/Backend/Sorts.php, Model/IndicesConfigurator.php, Model/Product/ReplicaManager.php, Model/Source/Sorts.php, Registry/ReplicaState.php, etc/adminhtml/system.xml
This PR introduces store scoped state management for replicas allowing highly selective changes to be persisted to Algolia minimizing the number of build operations on each store's respective index. 
All replica configuration persistence to Algolia is funneled through the new `ReplicaManager` class while backend models are used to track exactly what was changed for which affected stores via the `ReplicaState` singleton and the `ConfigChecker` utility class. 
Currently the `SaveSettings` observer iterates over all stores by default but replicas will not persist unless a change actually occurs for a given store. Changes to the default scope should not impact overridden websites or stores. Changes to a website should be localized to the associated store indices only (unless explicitly …
=> Feature/mage 839 Store scoped replica state management

README.md, composer.json
As Magento 2.4.7 now supports PHP 8.3, add this version to our own composer file.
=> MAGE-851: add PHP 8.3 compatibility to composer and README files

Api/Product/ReplicaManagerInterface.php, Exception/ReplicaLimitExceededException.php, Exception/TooManyCustomerGroupsAsReplicasException.php, Helper/ConfigHelper.php, Helper/Entity/ProductHelper.php, Model/Backend/EnableCustomerGroups.php, Model/Backend/Sorts.php, Model/Product/ReplicaManager.php, Model/Source/Sorts.php, Registry/ReplicaState.php, Validator/VirtualReplicaValidator.php
This PR aims to do the following:
- Introduce validation across replica operations (including admin and indexing) to ensure that granular sorting configurations do not create an undesirable virtual replica scenario.
- Clearly communicate to the end user what the cause of the replica error was, including calling out scenarios where customer group pricing is preventing the activation of virtual replicas.
- Automatically roll back any configuration changes made in the admin that will result in an invalid configuration and lead to an Algolia / Magento configuration mismatch.
- Link both customer group pricing enablement and sorting in the admin to the same underlying replica state so both can be validated independently.
- Maintain awareness of _applied_ scope in Magento and _affected_ stores …
=> Feature/mage 837 - virtual replica validator

view/frontend/web/internals/common.js
When we have a dynamically element  #algolia-search-box, we will get error when this element doesn't exists in DOM on the moment when we try to get him, this fix check it.
view/frontend/web/internals/common.js
```
var input = $(this).closest('#algolia-searchbox').find('input');
input.val('');
**input.length ?  input.get(0)?.dispatchEvent(new Event('input')) : null**
handleInputCrossAutocomplete(input);
```
=> MAGE-3 Checking on exists element fix

view/frontend/templates/recommend/cart/recommend_items.phtml, view/frontend/templates/recommend/products.phtml, view/frontend/templates/recommend/widget/trends-item.phtml, view/frontend/web/internals/recommend.css
This PR ports the change suggested by @sgeleon here: https://github.com/algolia/algoliasearch-magento-2/pull/1514
- Added a #algoliaRecommend block which acts as a parent for each recommend block
- Applied CSS on the recommend blocks, taking into account the newly created parent block
=> MAGE-947: restrict recommend CSS to algolia managed blocks

view/frontend/templates/internals/configuration.phtml, view/frontend/templates/layer/view.phtml
Following the previous PR : https://github.com/algolia/algoliasearch-magento-2/pull/1541#issuecomment-2190947847 , we now add a fallback for Magento 2.3 (where the SecureHtmlRenderer doesn't exists) as suggested by @hostep .
This PR also contains the removal of heredoc which is also not supported by Magento 2.3.x .
=> MAGE-949: SecureHtmlRenderer fallback for Magento2.3

Api/Console/ReplicaDeleteCommandInterface.php, Api/Console/ReplicaSyncCommandInterface.php, Api/Product/ReplicaManagerInterface.php, Console/Command/AbstractReplicaCommand.php, Console/Command/ReplicaCommand.php, Console/Command/ReplicaDeleteCommand.php, Console/Command/ReplicaRebuildCommand.php, Console/Command/ReplicaSyncCommand.php, Console/Traits/ReplicaDeleteCommandTrait.php, Console/Traits/ReplicaSyncCommandTrait.php, Helper/Entity/ProductHelper.php, Service/IndexNameFetcher.php, Service/Product/ReplicaManager.php, Service/StoreNameFetcher.php, etc/di.xml
This PR includes:
- Data cleanup operations in the `ReplicaManager` class
- Removal of unused and outdated replica method from `ProductHelper` class
- New `StoreNameFetcher` service
- Exposing index settings from `ProductHelper`
- New CLI namespace for store scoped replica management: `algolia:replicas` 
- CLI to manually initiate sync of replicas
- CLI to manually delete replicas (including identifying potentially unused replicas)
- CLI to manually rebuild replica configuration 
Sample interactions through CLI:
=> Feature/mage 938 - Replica CLI utilities 

Console/Command/AbstractReplicaCommand.php, Console/Command/ReplicaDeleteCommand.php, Console/Command/ReplicaDisableVirtualCommand.php, Console/Command/ReplicaRebuildCommand.php, Console/Command/ReplicaSyncCommand.php, Helper/ConfigHelper.php, Helper/Configuration/ConfigChecker.php, Service/Product/ReplicaManager.php, Service/Product/SortingTransformer.php, Setup/Patch/Data/MigrateConversionAnalyticsModePatch.php, Setup/Patch/Data/MigrateInstantSearchConfigPatch.php, Setup/Patch/Data/MigrateVirtualReplicaConfigPatch.php, Setup/Patch/Data/RebuildReplicasPatch.php, etc/di.xml
This PR includes:
- Refactored CLI classes for code reuse
- A new `disable-virtual-replicas` command to facilitate upgrades and allow a way to selectively roll back invalid configurations
- Forcing replica state on replica rebuilds to bypass Algolia API latency
- Bug fixes for the `ConfigChecker` class to handle more nested scoping config scenarios 
- A new data patch to migrate legacy global virtual configuration to granular sorting attribute configuration
- A new data patch to run after to fully rebuild the replica configuration 
- Error handling if replica limit is exceeded with detailed instructions on how to remedy (this should hopefully prevent upgrading with unexpected results to existing replica configurations)
Sample CLI output:
Sample `setup:upgrade` failure:
=> Feature/mage 848 - Granular virtual replica migration

CHANGELOG.md, README.md, composer.json, etc/module.xml
**Summary**
Release Notes:
Updates:
- Polyfill.io removed from CSP whitelist
- Hide Recommend Titles when not in use
- Incorporate community fix for higher specificity CSS selectors on Recommend
Bug Fix:
- Incorporate community fix for missing DOM element selector
=> MAGE-958: release number increased and change log updated

Helper/AlgoliaHelper.php
**Summary**
algoliaLastUpdateAtCET time changed to UTC timestamp
=> MAGE-909: algoliaLastUpdateAtCET time changed to UTC timestamp

README.md
**Summary**
Readme.md updated as follows:
- Since 1.x and 2.x reached EOL, all documentation related to those versions removed.
- PHP and Magento compatible versions included
=> MAGE-950: readme.md updated.

CHANGELOG.md, Setup/Patch/Data/RebuildReplicasPatch.php
This PR aims to address the "Area code is already set" error encountered during Marketplace technical review (could not reproduce on Adobe Commerce Cloud) and includes some missing updates in the change log.
=> Feature/mage 962 - RC2

Console/Command/ReplicaDeleteCommand.php, Console/Command/ReplicaDisableVirtualCommand.php, Console/Command/ReplicaRebuildCommand.php, Console/Command/ReplicaSyncCommand.php
This issue was identified by integration testing. 
During `setup:install`, Magento will perform dependency injection for all CLI commands. Unfortunately, if any constructor dependencies ultimately depend on the store manager this will trigger the dependency chain prematurely leading to the following error:
```
Base table or view not found: 1146 Table 'magento_integration_tests.flag' doesn't exist
```
By switching to proxies these dependencies are deferred until needed. 
NOTE: If not able to add to 3.14.0 let's tag for 3.14.1.
=> Feature/mage 962 - Integration test fix

view/frontend/web/js/autocomplete.js, view/frontend/web/js/internals/common.js
The URL formatted for Insights does not handle the case where URL already has parameters (which includes a "?"), this fix adds a "&" prior to the generated string in such case.  (see related ticket in MAGE-928).
=> MAGE-928: Fix generated url for insights

Helper/ConfigHelper.php, Helper/InsightsHelper.php, Observer/Insights/CookieRefresherObserver.php, Observer/Insights/CustomerLogout.php, etc/frontend/events.xml
Ensure authenticated and non-authenticated tokens lifetime:
On page load If the customer is logged in, we renew `_ALGOLIA_MAGENTO_AUTH`
In such case, the `web/cookie/cookie_lifetime` value from admin is applied to follow the `PHPSSESID` cookie lifetime
=> MAGE-891: Handle tokens expiration

view/frontend/web/js/autocomplete.js, view/frontend/web/js/internals/common.js
backport this change (https://github.com/algolia/algoliasearch-magento-2/pull/1583) for 3.13.6.
=> MAGE-928: Fix generated url for insights (3.13.6)

Console/Command/ReplicaDeleteCommand.php, Console/Command/ReplicaDisableVirtualCommand.php, Console/Command/ReplicaRebuildCommand.php, Console/Command/ReplicaSyncCommand.php, etc/di.xml
CodeSniffer yields a complaint on our injection method for proxy objects. Using `di.xml` over constructor is the preferred approach here.
Before applying fix:
After:
=> MAGE-1010 Fix Magento coding standards error with proxy injection

Block/Algolia.php, Helper/AlgoliaHelper.php, Helper/Data.php, Helper/Entity/ProductHelper.php, Model/IndexMover.php, Model/IndicesConfigurator.php
Extension now handles multi applications support for indexing:
- Products
- Categories
- Pages 
- Suggestions
Tested on two different applications (one with virtual replicas, the other one without virtual replicas), with and without indexing queue activated, for full reindex and reindex events.
TODO on this epic:
- Application validation refactoring
- Backend features testing
- Frontend features testing
- E2E testing
=> MAGE-979: Multi Apps indexing support

Block/Algolia.php, Helper/AdapterHelper.php, Helper/AlgoliaHelper.php, Helper/ConfigHelper.php, Helper/Configuration/AssetHelper.php, Helper/Configuration/NoticeHelper.php, Model/Indexer/AdditionalSection.php, Model/Indexer/Category.php, Model/Indexer/CategoryObserver.php, Model/Indexer/DeleteProduct.php, Model/Indexer/Page.php, Model/Indexer/PageObserver.php, Model/Indexer/Product.php, Model/Indexer/QueueRunner.php, Model/Indexer/Suggestion.php, Model/IndicesConfigurator.php, Model/Observer.php, Service/AlgoliaCredentialsManager.php, Setup/Patch/Data/RebuildReplicasPatch.php
Created an AlgoliaCredentialsManager class and centralize the credentials validation all accross the extension
- ApplicationID + Admin APIKey
```
$this->config->getApplicationID($storeId) && $this->config->getAPIKey($storeId)
// becomes
$this->algoliaCredentialsManager->checkCredentials($storeId)`
```
- ApplicationID + Admin APIKey + SearchOnly ApiKey
```
$this->configHelper->getApplicationID()
&& $this->configHelper->getAPIKey()
&& $this->configHelper->getSearchOnlyAPIKey()
// becomes
$this->algoliaCredentialsManager->checkCredentialsWithSearchOnlyAPIKey($storeId)
```
The algoliaCredentialsManager also handles the display of the error messages (both in console and Magento Admin)
⚠️ : In some places, it's impossible to define which store should be used, so I decided to make the `$storeId` …
=> MAGE-980: Application credentials validation

Block/Algolia.php, Helper/LandingPageHelper.php
This fixes a critical bug with landing pages render introduced in `3.14.0` by PHP strong typing on method return values. 
Creating a landing page for "blue shorts":
Store front render:
=> MAGE-1023 Fix landing page typing

Observer/AddAlgoliaAssetsObserver.php, etc/frontend/events.xml
Following this [PR](https://github.com/algolia/algoliasearch-magento-2/pull/1609) review, moving the Algolia Assets observer change to a separate branch/PR targeting 3.15.0-beta.
=> MAGE-1021: change Algolia assets observer class

Helper/Entity/ProductHelper.php
During the test for the multi-application IDs, I noticed that facet query rules configuration wasn't taken into account at store level. This change should fix it.
=> MAGE-983: Fix facet query rules at store level

Helper/Entity/CategoryHelper.php
Same PR as https://github.com/algolia/algoliasearch-magento-2/pull/1613 but targeting 3.13.6.
=> MAGE-970: Fix Category collection fetching (for 3.13.6)

Helper/AlgoliaHelper.php
This change includes:
- Removal of client creation in the constructor to avoid such issues in the future
- Prevented unhandled crash on category merchandising when no credentials are configured at Default level
- Feedback to the user is now handled by the `AlgoliaCredentialsManager` class
=> MAGE-1030: Fix client creation

Test/Integration/MultiStoreCategoriesTest.php, Test/Integration/MultiStoreConfigTest.php, Test/Integration/MultiStoreTestCase.php, Test/Integration/TestCase.php
This PR act as a POC for multi-stores bootstrap testing.
We create 2 additional stores and make sure that the extension creates appropriate number of indices in the application.
The `setupStore()` method allows to set different credentials per store, which will allow us to test multi applications scenarios in the future.
=> MAGE-1060: POC for multi-store indexing testing

Helper/Entity/PageHelper.php, Test/Integration/Page/MultiStorePagesTest.php
- Added new tests related to CMS Pages (multi-stores scenarios)
- Fixed a bug where excluded pages set at store level in the configuration weren't taken into account.
=> MAGE-1058: Add Multistores Pages tests

Helper/AlgoliaHelper.php, Setup/Patch/Schema/ConfigPatch.php, Test/Integration/Queue/QueueTest.php
- Refactored `QueueTest` class 
- Fix some config paths in `ConfigPatch` class
- Re-added all the skipped tests
- Fixed some flakiness issues where indices in jobs created in `testFill` and executed in `testExecute` didn't have the same prefix because they weren't run within the same second
- Fixed tests in `testGetJobs`
- Fixed moveIndex method (see JIRA ticket)
=> MAGE-1054: Fix queue tests

Helper/AlgoliaHelper.php
- Removed `mode` during `setSettings` if index has NeuralSearch enabled to prevent crash during full reindexing with temporary index creation.
=> MAGE-1093: Fix NeuralSearch compatibility

Test/Unit/ConfigHelperTest.php, Test/Unit/ConfigHelperTestable.php
- Fixed the following error coming from PHPCS
```
FILE: ...var/www/html/app/code/Algolia/AlgoliaSearch/Test/Unit/ConfigHelperTest.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
30 | ERROR | Each class must be in a file by itself
--------------------------------------------------------------------------------
```
=> MAGE-1078: Fix phpcs error

Block/Adminhtml/LandingPage/SearchConfiguration.php, Helper/Data.php, Helper/MerchandisingHelper.php, view/adminhtml/templates/landingpage/search-configuration.phtml, view/adminhtml/templates/query/edit/merchandising.phtml, view/adminhtml/web/js/components/query-merchandising.js
- Query Rules can now be created on multiple application using the Store View dropdown
- Category Merchandiser made compatible
- Query Merchandiser made compatible
- Landing Page Builder made compatible
=> MAGE-1032: Make Merchandising tools compatible with Multi-Application IDs

Controller/Adminhtml/Landingpage/Save.php
Fixed a bug where Landing Page save action failed when : 
- Customer groups are activated
- "Merchandised products" section has been expanded
- No price configuration within Landing Page Builder has been selected
=> MAGE-1145: Fix Landing Page creation when customer groups are enabled

Controller/Adminhtml/Landingpage/Save.php
Backported fix from https://github.com/algolia/algoliasearch-magento-2/pull/1647
Fixed a bug where Landing Page save action failed when :
- Customer groups are activated
- "Merchandised products" section has been expanded
- No price configuration within Landing Page Builder has been selected
=> MAGE-1145: Fix Landing Page creation when customer groups are enabled (3.14.4)

view/adminhtml/layout/algolia_algoliasearch_queuearchive_index.xml, view/adminhtml/templates/queuearchive/links.phtml
- Added documentation link on the queue archive page
=> MAGE-1074: Add documentation link on the queue archive page

Helper/AlgoliaHelper.php
- A fix where synonyms were systematically re-added after an index `setSettings()` call. Before v`3.14.x` this was previously handled with the old PHP client v3 with a `getVersion` query parameter set to `2` . We now unset the synonyms attribute since it has to be handled in the Algolia dashboard anyway.
=> MAGE-1153: fix synonyms duplication after PHP v4 upgrade

Helper/AlgoliaHelper.php
This PR backport the fix contained in this PR : https://github.com/algolia/algoliasearch-magento-2/pull/1656
> Fix where synonyms were systematically re-added after an index setSettings() call. Before v3.14.x this was previously handled with the old PHP client v3 with a getVersion query parameter set to 2 . We now unset the synonyms attribute since it has to be handled in the Algolia dashboard anyway.
=> MAGE-1153: fix synonyms duplication after PHP v4 upgrade (3.14.4)

Helper/ConfigHelper.php, Helper/Data.php, Model/Config/AutomaticPriceIndexingComment.php, Service/Product/MissingPriceIndexHandler.php, etc/adminhtml/system.xml, etc/config.xml, etc/indexer.xml
This will need rebasing against `release/3.14.4-dev` (to be discussed) but this PR provides a feature flagged auto price indexer to address missing pricing record dependencies at time of index.
Introduces injectable service `MissingPriceIndexHandler`.
Tested successfully against 3 major scenarios: 
1. Valid product record missing from price index BUT price index is not marked as invalid by Magento (product should NOT be removed from Algolia search index)
2. Price index is invalid (Price records should be reverified prior to search indexing)
3. Invalid product record  (out of stock etc) missing from price index (product SHOULD be removed from Algolia search index)
As price indexing is entity ID driven / store agnostic and indexing process is called for each store view, a caching …
=> MAGE-1122 intentional price indexing

Block/Configuration.php, Helper/AlgoliaHelper.php, Helper/ConfigHelper.php, Helper/Data.php, Helper/Entity/AdditionalSectionHelper.php, Helper/Entity/CategoryHelper.php, Helper/Entity/PageHelper.php, Helper/Entity/ProductHelper.php, Helper/Entity/SuggestionHelper.php, Helper/MerchandisingHelper.php, Model/IndexMover.php, Model/IndicesConfigurator.php, Service/AbstractIndexBuilder.php, Service/AdditionalSection/IndexBuilder.php, Service/AlgoliaConnector.php, Service/Category/IndexBuilder.php, Service/Page/IndexBuilder.php, Service/Product/BackendSearch.php, Service/Product/IndexBuilder.php, Service/Product/ReplicaManager.php, Service/Suggestion/IndexBuilder.php, Test/Integration/Category/MultiStoreCategoriesTest.php, Test/Integration/Config/MultiStoreConfigTest.php, Test/Integration/IndexingTestCase.php, Test/Integration/MultiStoreTestCase.php, Test/Integration/Page/MultiStorePagesTest.php, Test/Integration/Product/MultiStoreProductsTest.php
- Updated `AlgoliaHelper` by removing most of its logic. The main purpose of this class is now to handle the store context while communicating with the Algolia applications now that Multi-Application IDs has been introduced.
- Added `AlgoliaConnector` service which handles the logic previously handled by `AlgoliaHelper`
- Removed all the occurrences of `AlgoliaHelper::setStoreId() `all across the codebase (which was the main purpose of this refactoring)
- Updated all `AlgoliaHelper` methods which now include an optional `$storeId` parameter which ensure that the correct Algolia application is reached
- Fixed Page Tests for Magento 2.4.6
=> MAGE-1134: AlgoliaHelper refactoring

Controller/Adminhtml/Reindex/Save.php, Helper/ConfigHelper.php, Helper/Entity/ProductHelper.php, Model/Config/AutomaticPriceIndexingComment.php, Service/Product/IndexBuilder.php, Service/Product/MissingPriceIndexHandler.php, etc/adminhtml/system.xml, etc/config.xml, etc/indexer.xml
Refactor of https://github.com/algolia/algoliasearch-magento-2/pull/1662 for 3.15 (with profiling)
Some results:
On an extra large fixture (1M products) processing a delta of a 100 products took an additional 19 ms with virtually no RAM consumption:
Across a delta of 1000 products over 5 stores the process took 491 ms:
On the same size catalog, where 2000 price index records were found missing across 5 stores (but the price index still appears to be valid), the extra reindexing repair operations (on the fly) took approximately 592 ms and ~2.1 MB of RAM. 
Performance impact appears to be super linear but sub quadratic - approx. O(n^1.41) observed - and the upper boundary can be contained by the number of records processed per job. 
Full details in Jira.
=> MAGE-1122 Refactor intentional price indexing for 3.15

Controller/Adminhtml/Landingpage/Save.php
This PR backports the fix for Landing Page Builder added in this other PR: https://github.com/algolia/algoliasearch-magento-2/pull/1647
=> MAGE-1145: Fix Landing Page creation when customer groups are enabled (3.13.7)

Test/Integration/Config/MultiStoreConfigTest.php, Test/Integration/Config/Traits/ConfigAssertionsTrait.php, Test/Integration/Product/MultiStoreReplicaTest.php, Test/Integration/Product/ReplicaAssertionsTrait.php, Test/Integration/Product/ReplicaIndexingTest.php, Test/Integration/Product/Traits/ReplicaAssertionsTrait.php
- Added tests for Replicas with multi stores/applications context
- Created a `ReplicaAssertionsTrait` class which contains all the methods to be used by the `ReplicaIndexingTest` class AND the newly created `MultiStoreReplicaTest` class.
- Updated some methods of the `ReplicaAssertionsTrait` class to handle store switching
- Added a test for customer groups replicas
=> MAGE-1084: Multistore Replicas tests

Plugin/AddToCartRedirectForInsights.php, etc/frontend/di.xml, view/frontend/templates/instant/hit.phtml
This PR contains a fix where Insights information wasn't kept on a product page after the user tried to add it to cart on a page powered by instantsearch. 
If this product is for example a configurable one, they are redirected to the PDP to select the options (which is the expected Magento behaviour).
=> MAGE-1097: Handle add to cart redirect for Insights

Helper/Data.php
- Fixed a bug where remaining old product jobs in the queue prior setup upgrade could cause the process to display unwanted warning.
=> MAGE-1186: fix backward compatibility for old product jobs in queue

Service/Product/MissingPriceIndexHandler.php
Addresses PHP complaint per [Magento Coding Standard](https://experienceleague.adobe.com/en/docs/commerce-operations/upgrade-guide/upgrade-compatibility-tool/reporting/error-messages) (backported for v3.13).
=> MAGE-1179 Backport PHPCS fix to 3.13

CHANGELOG.md, Controller/Adminhtml/Landingpage/Save.php, Helper/AlgoliaHelper.php, Helper/ConfigHelper.php, Helper/Data.php, Model/Config/AutomaticPriceIndexingComment.php, Plugin/AddToCartRedirectForInsights.php, README.md, Service/Product/MissingPriceIndexHandler.php, composer.json, etc/adminhtml/system.xml, etc/config.xml, etc/frontend/di.xml, etc/indexer.xml, etc/module.xml, view/frontend/templates/instant/hit.phtml, view/frontend/web/js/internals/common.js
This PR updates main with changes from 3.14.4
- Added a feature to enable automatic price indexing on the Advanced section of the configuration (This feature should help alleviate issues where missing pricing records prevent Algolia from being able to index products.)
- Updated `getCookie` method to make it more consistent
- Removed dependency to `catalog_product_price` indexer
- Fixed a bug where the Landing Page Builder was crashing on save with customer group pricing was enabled.
- Fixed issue where Insights information wasn't kept on the url after clicking "add to cart" on PLP powered by InstantSearch
- Fixed a bug where synonyms were unintentionally duplicated on the Algolia dashboard
=> 3.14.4 to main

CHANGELOG.md
This PR updates the changelog for version `3.15.0` with all changes coming from `3.13.6`, `3.13.7` and `3.14.4` .
=> Update changelog file for 3.15.0

Api/Data/IndexOptionsInterface.php, Helper/AlgoliaHelper.php, Model/IndexOptions.php, Service/AlgoliaConnector.php, Service/IndexNameFetcher.php, Service/IndexOptionsBuilder.php
This PR contains: 
- Added an `IndexOptions` model implementing `IndexOptionsInterface` which would be the component of every index operation coming to `AlgoliaConnector` in the future
- Updated the deprecated `AlgoliaHelper` class to convert all calls to the new format including `IndexOptions` model
- Updated the `AlgoliaConnector` class so it fetches all index names according to the `InderNameFetcher` service
- Removed all the static methods in `AlgoliaConnector` to be able to use the IndexNameFetcher everywhere, notably in the `setLastOperationInfo` methid
=> MAGE-1170: Handle Index options with `IndexNameFetcher`

Model/Config/AutomaticPriceIndexingComment.php, Plugin/AddToCartRedirectForInsights.php, Service/Product/MissingPriceIndexHandler.php
Even though we do not officially support PHP 7 any longer (PHP 7.4 has not be supported since Magento 2.4.3 and support for that version [ended November 2022](https://experienceleague.adobe.com/en/docs/commerce-operations/release/versions#243)), version `3.13` of the Algolia extension has been compatible with PHP 7.4 to date. The recent release of `3.13.7` introduces newer PHP 8 syntax that could have an unintended impact to legacy installs. 
This PR reverts those constructs to preserve PHP 7 compatibility.
=> MAGE-1191 PHP 7 compatibility on last supported minor release

view/frontend/web/js/insights.js
This PR contains a small but necessary change from https://github.com/algolia/algoliasearch-magento-2/pull/1678 and is to be used in tandem with the Babel compilation steps from the companion PR outlined in Jira.
=> MAGE-1004 Babel transpiler fix

view/frontend/web/js/instantsearch.js, view/frontend/web/js/internals/template-engine.js
While [supplying updates](https://github.com/algolia/algoliasearch-custom-algolia-magento-2/pull/15) to our `CustomAlgolia` module to demonstrate the ability to use mixins with the updated `3.15.0` libraries I decide to refactor a few more bits of functionality on InstantSearch to expose setup functions without getting too ambitious. 
There's more work that needs to be done here as the legacy code makes heavy use of closures in what is presently contained in a pretty monolithic `buildInstantSearch` method. I realize we expose `allWidgetConfiguration` for modification through our hooks, but I feel it would also be very convenient to be able to granularly override things through a simple mixin. Future updates here can expose more internals in these JavaScript files to customization without …
=> MAGE-1061 Adding support for additional IS mixins

Api/RecordBuilder/RecordBuilderInterface.php, Helper/Entity/AbstractEntityHelper.php, Helper/Entity/AdditionalSectionHelper.php, Helper/Entity/CategoryHelper.php, Helper/Entity/PageHelper.php, Helper/Entity/ProductHelper.php, Helper/Entity/SuggestionHelper.php, Service/AdditionalSection/RecordBuilder.php, Service/Category/RecordBuilder.php, Service/Page/RecordBuilder.php, Service/Product/RecordBuilder.php, Service/Suggestion/RecordBuilder.php
- Updated `AbstractEntityHelper` with a new `getIndexSettings` method to implement
- Introduced `RecordBuilderInterface`
- Introduced a `RecordBuilder` per Entity which is now responsible for formatting any record sent to Algolia
- Updated each Entity Helpers which are now freed from such responsibility
- As a consequence, `getObject` methods from Entity Helpers are now deprecated and will be removed in version 3.16.0 in favour of `RecordBuilderInterface::buildRecord` which is much more self-explanatory
=> MAGE-1184: Entity Helpers refactoring

Console/Command/AbstractReplicaCommand.php, Console/Command/AbstractStoreCommand.php, Console/Command/ReplicaDeleteCommand.php, Console/Command/ReplicaDisableVirtualCommand.php, Console/Command/ReplicaRebuildCommand.php, Console/Command/ReplicaSyncCommand.php, Console/Command/SynonymDeduplicateCommand.php, Helper/AlgoliaHelper.php, etc/di.xml
This is an experimental synonym deduplicator that handles 3 of the 4 possible synonym types using the current PHP API client v4. Enhancement of the API will be necessary to support a more comprehensive solution.
=> MAGE-1153 Synonym deduplicator

Helper/Entity/ProductHelper.php, Model/Source/Facets.php, Service/Product/FacetBuilder.php, Test/Unit/AlgoliaLoggerTest.php, Test/Unit/Helper/ConfigHelperTest.php, Test/Unit/Helper/ConfigHelperTestable.php, Test/Unit/Logger/AlgoliaLoggerTest.php, Test/Unit/Logger/DiagnosticLoggerTest.php, Test/Unit/Service/Product/FacetBuilderTest.php, Test/Unit/Service/Product/FacetBuilderTestable.php, etc/adminhtml/system.xml
**Summary**
This primary of objective of this PR is introduce default `renderingContent` that will help power `dynamicWidgets`. It also includes some refactoring:
- New `FacetBuilder` service
- Shared `rawFacets` between `renderingContent` and `attributesForFaceting`
- Separating logic into functions by area of concern: groups, categories,
- Introducing constants for Magento integration specific key conventions
- Added unit tests and reorganized existing
During implementation it was observed that our currency handling is flawed as it does not handle scoped currency config by store but this PR does not address that issue. That will be addressed in a separate ticket. 
**Result**
`renderingContent` persisted as Facet Display in Dashboard:
All tests passed (including reorganized tests)
=> MAGE-973 Default renderingContent

Test/Unit/AlgoliaLoggerTest.php
**Summary**
Switching to virtual types broke some unit tests. This fixes this issue. 
**Result**
Before:
After:
=> MAGE-1228 Fix unit tests for 3.15.0 release

Block/Adminhtml/Reindex/AbstractReindexAllButton.php, Block/Adminhtml/Reindex/ReindexAll/Page.php, Block/Adminhtml/Reindex/ReindexAll/Product.php, Controller/Adminhtml/IndexingManager/Reindex.php, view/adminhtml/ui_component/cms_page_listing.xml, view/adminhtml/ui_component/product_listing.xml
- Added a "Reindex to Algolia" option in the dropdown situated on top of the products and pages grid, which allows the user to select products/pages with the grid checkboxes and perform a reindex for the selected entities
- Added a "Reindex All Items" button on the top of the pages to perform a full reindex for those entities, reusing the `Reindex` controller introduced by the Indexing manager. 
- Introduced the possibility to set a redirect path after the reindexing
- Improved the success messages after a reindex (it now varies depending on if the queue is activated or not and displays the impacted number of entities if it's coming from the grid)
=> MAGE-1224: Add reindexing features in products and pages grid

etc/di.xml
**Summary**
This addresses an install issue encountered on Community Edition when installing Algolia via Composer before Magento. It uses proxies to defer the dependency chain that attempts to access store config before it has been defined. 
The error resolved is: "In WebsiteRepository.php line 159:  The default website isn't defined. Set the website and try again."
**Result**
Before fix:
After fix:
=> MAGE-1228 Add proxies to constructor to defer store ops

Api/Product/ReplicaManagerInterface.php, Service/Product/ReplicaManager.php, Setup/Patch/Data/RebuildReplicasPatch.php, Test/Integration/Product/ReplicaIndexingTest.php, Test/Integration/TestCase.php, Test/Unit/Service/ReplicaManagerTest.php, Test/Unit/Service/ReplicaManagerTestable.php, etc/di.xml
**Summary**
The PR aims to add robustness to handling replica operations when the API behaves unexpectedly. 
- Added replica specific delete method to `ReplicaManager` with an optional pre-validation step to ensure indices are not still in an attached state before attempting deletion
- Enforced additional pre validation for data patch calls to delete operations
- Refactored patch to be non blocking to CI/CD
- Added a retry mechanism to the data patch to address potential latency and/or accuracy issues with underlying PHP API client `waitForTask` operations
- Revised enablement logic to take into account stores without backend render active but still using InstantSearch 
- Added unit tests to ReplicaManager
- Added new and refactored existing integration tests for applying data patches for …
=> MAGE-1218 Replica management enhancements - data patch fix / tests

Model/Indexer/Category.php, Model/Indexer/CategoryObserver.php, Service/Category/BatchQueueProcessor.php
- A fix to the way the Category indexer handles the products reindexing a category contains when the CategoryObserver is triggered (an issue was introduced with the refactoring of the indexers). 
Tests on the Category indexing will be part of an upcoming effort
=> MAGE-1244: Fix `$affectedProductIds` logic

Controller/Adminhtml/Reindex/Save.php
**Summary**
Fix for ugly error when creds aren't confgured.
**Result**
Before:
After:
=> MAGE-1228 Fix error on invalid creds when using manual SKU indexer

Controller/Adminhtml/Reindex/Save.php
Backport fix from https://github.com/algolia/algoliasearch-magento-2/pull/1722 for v3.14.x.
=> MAGE-1228 Fix error on invalid creds when using manual SKU indexer (3.14.x) 

CHANGELOG.md, composer.json
- updated changelog with the latest fix
- pinned PHP Client version to 4.18.3
=> MAGE-1228: updated changelog + pin PHP client version

etc/adminhtml/system.xml
**Summary**
In version 3.14, in an effort to enhance UX and make configuration impact clearer, we introduced Magento admin config dependencies on InstantSearch elements such as "Faceting" and "Sorting". A side effect of this change is the way Magento handles hidden elements that use the backend model: `\Magento\Config\Model\Config\Backend\Serialized`. If InstantSearch is disabled, complex configuration like Faceting and Sorting will be lost. This may be undesirable behavior when experimenting with Algolia admin configurations. For this reason we are removing all dependencies on `algoliasearch_instant/instant/is_instant_enabled` in version 3.16. 
**Result**
=> MAGE-1259 Remove InstantSearch enablement dependency in Magento admin

Service/Product/FacetBuilder.php, Test/Unit/Service/Product/FacetBuilderTest.php
**Summary**
This PR:
- Ensures `categories.level0` is included in `attributesForFaceting` when applicable (when category PLP is enabled _or_ categories facet selected in admin) to enable selection in rules
- Cleans up `renderingContent` to exclude non relevant attributes like merch meta data.
- Adds unit tests for expected facet scenarios
**Result**
Selecting `level0` in rules editor:
Unit tests:
=> MAGE-1258 Rule editor friendly categories

Api/Product/ReplicaManagerInterface.php, Service/Product/ReplicaManager.php, Setup/Patch/Data/RebuildReplicasPatch.php, Test/Integration/Indexing/Product/MultiStoreReplicaTest.php, Test/Integration/Indexing/Product/ReplicaIndexingTest.php, Test/Integration/Indexing/Product/Traits/ReplicaAssertionsTrait.php, Test/Integration/TestCase.php, Test/Unit/Service/ReplicaManagerTest.php, Test/Unit/Service/ReplicaManagerTestable.php
**Summary**
This PR in includes the updates from https://github.com/algolia/algoliasearch-magento-2/pull/1741 
**Result**
Verified on 3.16.0-beta
Integration tests
Unit tests
Magento vs Algolia
=> MAGE-1251 Replica enhancements ported to 3.16

Service/Product/ReplicaManager.php, Test/Unit/Service/ReplicaManagerTest.php
**Summary**
This PR backports a fix to the detach replica logic. An issue was identified while porting replica changes for 3.14 (on https://github.com/algolia/algoliasearch-magento-2/pull/1718) to 3.15 (on https://github.com/algolia/algoliasearch-magento-2/pull/1741).
**Result**
Unit tests
Integration tests
=> MAGE-1251 Fix replica detach operation for 3.14

Api/LoggerInterface.php, Logger/AlgoliaLogger.php, Logger/TimedLogger.php, Observer/Insights/CheckoutCartProductAddAfter.php, Observer/Insights/CheckoutOnePageControllerSuccessAction.php, Observer/Insights/WishlistProductAddAfter.php, Observer/RecommendSettings.php, Setup/Patch/Data/RebuildReplicasPatch.php, Test/Unit/Logger/AlgoliaLoggerTest.php, etc/di.xml
**Summary**
This PR is a proposed change while implementing https://github.com/algolia/algoliasearch-magento-2/pull/1752 that switches from a virtual type logger to a concrete logger which can be referenced in code (unlike the previous virtual type). It is intended as a drop in replacement for `Psr\Log\LoggerInterface` and to provide a simple way to localize Algolia specific logging without needing to inject the heavier `DiagnosticsLogger` or `TimedLogger`.
**Result**
=> MAGE-1272 Concrete injectable logger

Helper/ConfigHelper.php, Helper/Data.php, Helper/Entity/PageHelper.php, Service/AbstractIndexBuilder.php, Service/Product/ReplicaManager.php, Setup/Patch/Data/MigrateIndexingConfigPatch.php, Setup/Patch/Schema/ConfigPatch.php, Test/Integration/Indexing/Product/ReplicaIndexingTest.php, Test/Integration/_files/second_website_with_two_stores_and_products.php, etc/adminhtml/system.xml, etc/config.xml, view/adminhtml/web/js/config.js
- Moved indexing configuration from "Credentials and Basic setup" section to the newly created "Indexing Manager" section
- Renamed "Enable Backend" occurrences to "Enable Indexing" to be more meaningful and to avoid confusion with "backend rendering" statements in the extension.
- Fixed tests according to these changes
- Added a data patch to ensure the configuration doesn't get lost in the process.
=> MAGE-1270: Move indexing configuration to the indexing manager

Helper/ConfigHelper.php, Helper/Configuration/QueueHelper.php, Service/Product/BatchQueueProcessor.php, Service/Product/IndexBuilder.php, Setup/Patch/Schema/ConfigPatch.php, Test/Integration/Indexing/Queue/QueueTest.php, Ui/Component/Listing/Column/Data.php, etc/adminhtml/system.xml, etc/config.xml
- Added "Use temporary index for full products reindex" config to the indexing queue section
- Updated to product batch processing to take this new config into
- Added a small improvement to the Indexing Queue Data column so it now indicates clearly if a temporary index is used in the job or not.
- Added an integration test which ensure that no temporary index is created in case this config is set to "No"
- Recent change on this PR for 3.17.0 introduced `$tmpTmpIndex` to `Product/IndexBuilder::indexPage()` . This changes worked for 3.16.0 but another PR for 3.17.0 removed the parameter: https://github.com/algolia/algoliasearch-magento-2/pull/1764/files#diff-0251b76d832bc7f8f1205481909f582d196147fa77188441b39a86a7885ac3a3L107 => This PR also fixes this issue so it works …
=> MAGE-1138: Configurable temporary index usage

Test/Integration/Frontend/Category/CategoryCacheTest.php, Test/Integration/TestCase.php, Test/Unit/Controller/Adminhtml/IndexingManager/ReindexTest.php, Test/Unit/Logger/Handler/AbstractHandlerTestCase.php, Test/Unit/Logger/Handler/AlgoliaLoggerHandlerTest.php, Test/Unit/Logger/Handler/SystemLoggerHandlerTest.php, Test/Unit/Model/Backend/QueueCronTest.php, Test/Unit/Service/EventProcessorTest.php, composer.json
**Summary**
This PR addresses concerns related to compatibility with PHPUnit 10 in preparation for Magento 2.4.8 as recommended here: https://experienceleague.adobe.com/en/docs/commerce-operations/release/notes/adobe-commerce/2-4-8#platform
**Result**
Unit tests work as expected on PHPUnit 10
Integration tests will need to be refactored further for compatibility.
=> MAGE-1363 PHPUnit 10 prep

Helper/ConfigHelper.php, Helper/Configuration/NoticeHelper.php, Service/Product/RecordBuilder.php, Test/Integration/Indexing/Product/ProductsIndexingTest.php
- Make the `price` attribute optional => now it shouldn't be indexed if the price attribute is **not** present in the **product attributes**, the **sortings**, the **facets** and the **custom rankings** lists.
- Display a notice in the admin when the user removes the `price` attribute from the attributes list but not from another list (which would make the `price` attribute still indexed)
- Updated the product indexing integration test to ensure this new logic is applied.
=> MAGE-1112: Make `price` attribute optional during product indexing

CHANGELOG.md, Plugin/RenderingCacheContextPlugin.php, Setup/Patch/Schema/ConfigPatch.php, Test/Unit/Plugin/RenderingCacheContextPluginTest.php, composer.json, etc/config.xml
**Summary**
The legacy cache handling has been observed to break with Varnish due to inconsistent setting of the `X-Magento-Vary cookie` across requests.
This PR aims to correct this by the following:
- Disable cache manipulation by default to preclude Varnish `MISS` on category PLP on an non-configured Magento instance
- This change is dependent on the InstantSearch replace categories feature which now must be explicitly enabled on new instances aligning with our documentation: https://www.algolia.com/doc/integration/magento-2/guides/category-pages/#enable-category-pages
- Remove conditional behavior on setting the vary string from the plugin on `\Magento\Framework\App\Http\Context` so that a consistent `X-Magento-Vary` cookie is sent across all requests based on user context.
**Result** …
=> MAGE-1378 Fix handling of Varnish X-Magento-Vary cookie

Model/Job.php, Model/Queue.php, Service/Category/BatchQueueProcessor.php, Service/Category/IndexBuilder.php, Service/Product/BatchQueueProcessor.php, Service/Suggestion/IndexBuilder.php, Test/Integration/Indexing/Queue/QueueTest.php
- Some cleaning on the `Queue` and `Job` models
- A new way of calculating maximum batch size in the queue, now we take into account the values defined at store level instead of the default one. This allows to take the values set by the batching optimizer into consideration.
- Added some missing store scopings
- Fixed a merge test
=> MAGE-1110: Indexing Queue updates

view/adminhtml/templates/queue/status.phtml
- Backport the fix from https://github.com/algolia/algoliasearch-magento-2/pull/1804 for 3.16.1
=> MAGE-1393: fixed indexing queue notices display in phtml  (3.16.1)

CHANGELOG.md, Model/Queue.php, composer.json, etc/module.xml
**Summary**
This resolves the issue with `setup:upgrade` throwing a missing interceptor exception on v3.17 on PHP 8.4.
```
Class "Algolia\AlgoliaSearch\Console\Command\Queue\ProcessQueueCommand\Interceptor" does not exist
```
**Result**
Successful `setup:upgrade` + Verified with PHPCS:
```
composer require --dev slevomat/coding-standard
vendor/bin/phpcs \
--standard=SlevomatCodingStandard \
--sniffs=SlevomatCodingStandard.TypeHints.NullableTypeForNullDefaultValue \
--runtime-set testVersion 8.4 \
--extensions=php \
vendor/algolia/algoliasearch-magento-2
```
=> MAGE-1413 Fix implicit nullable types for PHP 8.4

view/frontend/web/js/template/autocomplete/products.js
**Summary**
Autocomplete will render a non-clickable link on a no results search.
**Result**
**Steps to Recreate**
1. Navigate to a page that has Algolia Autocomplete enabled on it
2. Perform a search that will return no results
- BUG: observe the link to **All Departments** is not clickable
=> MAGE-1421 Don't Render non-clickable Link

Helper/Entity/Product/PriceManager/ProductWithChildren.php
**Summary**
`$this->getSpecialPrice()` and `$this->getTierPrice()` Return a converted price when using multiple currencies, however these prices there converted again a little bit further down the function
Example: Base Currency GBP, Product Price 1200, also shows prices in EUR with a conversion rate of 1.2 (simplified numbers for example)
[`$this->getSpecialPrice()` ](https://github.com/algolia/algoliasearch-magento-2/blob/3ecbf4e1313a3b19a85c2c9dc89b027447e0d286/Helper/Entity/Product/PriceManager/ProductWithoutChildren.php#L260) will return the Product Final price but converted (1200 * 1.2 = 1440) and then this gets converted again on line 72 (1440 * 1.2 = 1728) giving us an incorrect amount.
I have refactored the currency conversion to convert just the final Price and Base Price so …
=> Refactor Product With Children to remove Double Conversion

Helper/Entity/Product/PriceManager/ProductWithChildren.php
This PR backports the fix for double conversion issue on products with children from this PR : https://github.com/algolia/algoliasearch-magento-2/pull/1745
=> MAGE-1335: Refactor Product With Children to remove Double Conversion (3.15.2)

Helper/Entity/Product/PriceManager/ProductWithChildren.php
This PR backports the fix for double conversion issue on products with children from this PR : https://github.com/algolia/algoliasearch-magento-2/pull/1745
=> MAGE-1335: Refactor Product With Children to remove Double Conversion (3.16.1)

Setup/Patch/Data/MigrateBatchSizeConfigPatch.php, Setup/Patch/Data/MigrateIndexingConfigPatch.php, Setup/Patch/Data/MigrateInstantSearchConfigPatch.php, Setup/Patch/DataMigrationTrait.php
- Added a `DataMigrationTrait.php` class which handles the data migration in the `core_config_data` table in the data patches.
- Introduced a check before performing the update statement, which should prevent some "Integrity constraint violation" issues which can occur in some circumstances.
=> MAGE-1404: Add checks on configuration migration processed on data patches

Setup/Patch/Data/MigrateInstantSearchConfigPatch.php
This PR backports changes from https://github.com/algolia/algoliasearch-magento-2/pull/1817 for v 3.15.2.
=> MAGE-1404: Add checks on configuration migration processed on data patches (3.15.2)

Helper/ConfigHelper.php, Helper/Entity/Product/PriceManager/ProductWithChildren.php, Helper/Entity/Product/PriceManager/ProductWithoutChildren.php, Test/Unit/Helper/ConfigHelperTest.php, etc/adminhtml/system.xml
- Added (limited) compatibility with FPT Magento feature (as suggested in this earlier PR: https://github.com/algolia/algoliasearch-magento-2/pull/1619) (thanks @aissyass)
⚠️ : We only support FPT set at country level (not state scoped ones)
- Added Configuration in the "Advanced" section of the extension's configuration to enable/disable this feature (FPT also has to be enabled in the default **Sales > Tax > Fixed Product Taxes** section).
=> MAGE-1070: Add FPT compatibility

.circleci/config.yml, CHANGELOG.md, Model/Product/Url.php
**Summary**
- Includes community supplied fix from https://github.com/algolia/algoliasearch-magento-2/pull/1796
- Restricts CI to only execute on `feat`, `fix` & `chore`
=> MAGE-1422 Product URL fix for 3.16.1

Service/Insights/EventProcessor.php
**Summary**
Adding a product to the cart may trigger a PHP and Algolia error due to the discount amount being too large due to improper math by PHP.
```
php -v
PHP 8.2.28 (cli) (built: Mar 13 2025 18:13:24) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.28, Copyright (c) Zend Technologies
with Zend OPcache v8.2.28, Copyright (c), by Zend Technologies
with Xdebug v3.4.2, Copyright (c) 2002-2025, by Derick Rethans
```
**Result**
This error is thrown in `var/log/system.log`
```
main.CRITICAL: Unable to send add to cart event due to Algolia events model misconfiguration: Discount must be a valid decimal number and total length must be no longer than 16 characters [] []
```
A `422` status code is returned in the Algolia Events Debugger.
Here using xdebug in PHPStorm we can see what is …
=> MAGE-1419 Prevent 422 Insights Event - Add to Cart with Discount

CHANGELOG.md, Model/Queue.php
This PR contains changes from @pikulsky in their original PR:  https://github.com/algolia/algoliasearch-magento-2/pull/1769
- Fix using queue job's store ID for jobs sorting
=> MAGE-1420: Fix store id for queue job (3.17.0)

CHANGELOG.md, Model/Job.php, Model/Queue.php
This PR contains changes from @pikulsky in their original PR:  https://github.com/algolia/algoliasearch-magento-2/pull/1769
- Follow camel case for store ID
- Fix using queue job's store ID for jobs sorting
=> MAGE-1420: Fix store id for queue job (3.15.2)
